
/* global describe, it, expect */
describe("ResourceEditSpec", function() {

    beforeEach(function() {
    });
    
    it("produces form inputs",function(){
        jasmine.getFixtures().fixturesPath = "base/src/main/webapp/";
        var html = jasmine.getFixtures().read("WEB-INF/content/resource/vue-file-upload-template.html");
        html = html + jasmine.getFixtures().read("components/tdar-autocomplete/template/autocomplete.html");
        html = html + jasmine.getFixtures().read("components/tdar-taggging/template/tagging.html");
        html = html + jasmine.getFixtures().read("components/tdar-values/template/values.html");
        html = html + jasmine.getFixtures().read("WEB-INF/macros/creatorwidget.html");
        html = html + jasmine.getFixtures().read("WEB-INF/macros/inheritance.html");
        var script = "<script id='json' type='text/json'>" + JSON.stringify(dataToLoad) + "</script>"; 
        var fix = jasmine.getFixtures().set(html  + script);
        var  vapp = TDAR.vuejs.resourceEdit.init("#sel");

    });

var dataToLoad = { "spaceInBytesUsed": 11270276,
	"filesUsed": 2,
	"previousSpaceInBytesUsed": 0,
	"previousFilesUsed": 0,
	"title": "201 Survey and Test Excavations, Lake City, Florida: Testing a Site Complex at Alligator Lake",
	"description": "This resource is a citation record only, the Center for Digital Antiquity does not have a copy of this document. " +
			"The information in this record has been migrated into tDAR from the National Archaeological Database Reports Module (NADB-R) and updated. Most NADB-R records consist of a" +
			" document citation and other metadata but do not have the documents themselves uploaded.\r\n\r\nIf you have a digital copy of the document and would like to have it curated in " +
			"tDAR,please contact us at comments@tdar.org.",
	"formattedDescription": null,
	"dateCreated": "2011-07-15T23:39:34-07:00",
	"url": "",
	"resourceType": "DOCUMENT",
	"previousStatus": null,
	"unmanagedResourceCollections": [],
	"externalId": null,
	"metadataLanguage": null,
	"resourceLanguage": "ENGLISH",
	"doi": "",
	"copyLocation": "FDAHRM, Tallahassee,Florida [164]",
	"lastUploaded": null,
	"date": 1982,
	"resourceProviderInstitution": null,
	"publisher": null,
	"publisherLocation": "",
	"inheritingInvestigationInformation": false,
	"inheritingSiteInformation": false,
	"inheritingMaterialInformation": false,
	"inheritingOtherInformation": false,
	"inheritingCulturalInformation": false,
	"inheritingSpatialInformation": false,
	"inheritingTemporalInformation": false,
	"inheritingNoteInformation": false,
	"inheritingIdentifierInformation": false,
	"inheritingCollectionInformation": false,
	"inheritingIndividualAndInstitutionalCredit": false,
	"mappedDataKeyColumn": null,
	"mappedDataKeyValue": null,
	"documentType": "BOOK",
	"documentSubType": null,
	"degree": null,
	"seriesName": "",
	"seriesNumber": "",
	"numberOfPages": null,
	"edition": "",
	"isbn": "",
	"bookTitle": "",
	"issn": "",
	"startPage": "",
	"endPage": "",
	"journalName": "",
	"volume": "",
	"numberOfVolumes": null,
	"journalNumber": "",
	"totalNumberOfPages": 13,
	"activeApprovedSiteTypeKeywords": [],
	"activeUncontrolledSiteTypeKeywords": [],
	"activeApprovedCultureKeywords": [],
	"activeUncontrolledCultureKeywords": [ { "label": "Leon Jefferson Period",
	"synonyms": [],
	"occurrence": 5,
	"urlNamespace": "browse/culture-keyword",
	"slug": "leon-jefferson-period",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2848/leon-jefferson-period",
	"synonymFormattedName": "Leon Jefferson Period",
	"id": 2848,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] },
	{ "label": "Alachua Period",
	"synonyms": [],
	"occurrence": 8,
	"urlNamespace": "browse/culture-keyword",
	"slug": "alachua-period",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2849/alachua-period",
	"synonymFormattedName": "Alachua Period",
	"id": 2849,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] },
	{ "label": "Lochloosa Punctated Sherd",
	"synonyms": [],
	"occurrence": 2,
	"urlNamespace": "browse/culture-keyword",
	"slug": "lochloosa-punctated-sherd",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2850/lochloosa-punctated-sherd",
	"synonymFormattedName": "Lochloosa Punctated Sherd",
	"id": 2850,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] } ],
	"activeManagedGeographicKeywords": [],
	"publisherName": null,
	"activeLatitudeLongitudeBoxes": [ { "obfuscatedSouth": 29.825592041015625,
	"obfuscatedWest": -82.80048370361328,
	"obfuscatedNorth": 30.597740173339844,
	"obfuscatedEast": -82.4525146484375,
	"south": 29.825592041015625,
	"north": 30.597740173339844,
	"west": -82.80048370361328,
	"east": -82.4525146484375,
	"geographicKeywords": null,
	"initialized": true,
	"centerLatitudeIfNotObfuscated": 30.211666107177734,
	"centerLongitudeIfNotObfuscated": -82.62649917602539,
	"obfuscatedCenterLatitude": 30.211666107177734,
	"obfuscatedCenterLongitude": -82.62649917602539,
	"centerLatitude": 30.211666107177734,
	"centerLongitude": -82.62649917602539,
	"obfuscatedArea": 0.2686836560606025,
	"obfuscatedAbsoluteLatLength": 0.7721481323242188,
	"obfuscatedAbsoluteLongLength": 0.34796905517578125,
	"absoluteLatLength": 0.7721481323242188,
	"absoluteLongLength": 0.34796905517578125,
	"maximumLatitude": 30.597740173339844,
	"minimumLatitude": 29.825592041015625,
	"maximumLongitude": -82.4525146484375,
	"minimumLongitude": -82.80048370361328,
	"initializedAndValid": true,
	"area": 0.2686836560606025,
	"id": 426990,
	"okayToShowExactLocation": false } ],
	"activeResourceAnnotations": [ { "resourceAnnotationKey": { "key": "NADB citation id number",
	"formatString": null,
	"id": 18,
	"resourceAnnotationType": "IDENTIFIER",
	"annotationDataType": null },
	"value": "000000048310",
	"pairedValue": "NADB citation id number:000000048310",
	"id": 866844 },
	{ "resourceAnnotationKey": { "key": "NADB document id number",
	"formatString": null,
	"id": 19,
	"resourceAnnotationType": "IDENTIFIER",
	"annotationDataType": null },
	"value": "353565",
	"pairedValue": "NADB document id number:353565",
	"id": 866843 } ],
	"totalNumberOfActiveFiles": 2,
	"activeResourceCreators": [ { "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 172,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": null,
	"url": null,
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"email": null,
	"creatorType": "INSTITUTION",
	"properName": "fDAHRM",
	"label": "fDAHRM",
	"title": "fDAHRM",
	"detailUrl": "/browse/creators/47359/fdahrm",
	"slug": "fdahrm",
	"synonymFormattedName": "fDAHRM",
	"institutionName": null,
	"urlNamespace": "browse/creators",
	"id": 47359,
	"status": "ACTIVE",
	"name": "fDAHRM",
	"parentRef": null,
	"synonyms": [] },
	"id": 284958,
	"sequenceNumber": 2,
	"role": "SPONSOR" },
	{ "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 72,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": null,
	"url": null,
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"lastName": "Chance",
	"firstName": "Marsha A.",
	"orcidId": null,
	"email": null,
	"emailPublic": false,
	"institution": null,
	"rpaNumber": null,
	"phone": null,
	"phonePublic": false,
	"registered": false,
	"creatorType": "PERSON",
	"properName": "Marsha A. Chance",
	"label": "Chance, Marsha A.",
	"title": "Marsha A. Chance",
	"detailUrl": "/browse/creators/47360/marsha-a-chance",
	"slug": "marsha-a-chance",
	"synonymFormattedName": "Marsha A. Chance",
	"urlNamespace": "browse/creators",
	"id": 47360,
	"status": "ACTIVE",
	"synonyms": [] },
	"id": 284959,
	"sequenceNumber": 0,
	"role": "AUTHOR" },
	{ "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 19928,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": "",
	"url": "",
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"email": null,
	"creatorType": "INSTITUTION",
	"properName": "State, County, and Local Government",
	"label": "State, County, and Local Government",
	"title": "State, County, and Local Government",
	"detailUrl": "/browse/creators/12729/state-county-and-local-government",
	"slug": "state-county-and-local-government",
	"synonymFormattedName": "State, County, and Local Government",
	"institutionName": null,
	"urlNamespace": "browse/creators",
	"id": 12729,
	"status": "ACTIVE",
	"name": "State, County, and Local Government",
	"parentRef": null,
	"synonyms": [] },
	"id": 284960,
	"sequenceNumber": 1,
	"role": "SPONSOR" } ],
	"totalNumberOfFiles": 2,
	"activeCultureKeywords": [ { "label": "Leon Jefferson Period",
	"synonyms": [],
	"occurrence": 5,
	"urlNamespace": "browse/culture-keyword",
	"slug": "leon-jefferson-period",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2848/leon-jefferson-period",
	"synonymFormattedName": "Leon Jefferson Period",
	"id": 2848,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] },
	{ "label": "Alachua Period",
	"synonyms": [],
	"occurrence": 8,
	"urlNamespace": "browse/culture-keyword",
	"slug": "alachua-period",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2849/alachua-period",
	"synonymFormattedName": "Alachua Period",
	"id": 2849,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] },
	{ "label": "Lochloosa Punctated Sherd",
	"synonyms": [],
	"occurrence": 2,
	"urlNamespace": "browse/culture-keyword",
	"slug": "lochloosa-punctated-sherd",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2850/lochloosa-punctated-sherd",
	"synonymFormattedName": "Lochloosa Punctated Sherd",
	"id": 2850,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] } ],
	"activeInvestigationTypes": [ { "label": "Data Recovery / Excavation",
	"synonyms": [],
	"occurrence": 14626,
	"urlNamespace": "browse/investigation-type",
	"slug": "data-recovery-excavation",
	"dedupable": true,
	"detailUrl": "/browse/investigation-type/5/data-recovery-excavation",
	"synonymFormattedName": "Data Recovery / Excavation",
	"id": 5,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Site Evaluation / Testing",
	"synonyms": [],
	"occurrence": 96489,
	"urlNamespace": "browse/investigation-type",
	"slug": "site-evaluation-testing",
	"dedupable": true,
	"detailUrl": "/browse/investigation-type/10/site-evaluation-testing",
	"synonymFormattedName": "Site Evaluation / Testing",
	"id": 10,
	"status": "ACTIVE",
	"assertions": [] } ],
	"activeTemporalKeywords": [ { "label": "Protohistoric Period",
	"synonyms": [],
	"occurrence": 70,
	"urlNamespace": "browse/temporal-keyword",
	"slug": "protohistoric-period",
	"dedupable": true,
	"detailUrl": "/browse/temporal-keyword/161/protohistoric-period",
	"synonymFormattedName": "Protohistoric Period",
	"id": 161,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "1499-1000 A.D.",
	"synonyms": [],
	"occurrence": 3,
	"urlNamespace": "browse/temporal-keyword",
	"slug": "1499-1000-ad",
	"dedupable": true,
	"detailUrl": "/browse/temporal-keyword/839/1499-1000-ad",
	"synonymFormattedName": "1499-1000 A.D.",
	"id": 839,
	"status": "ACTIVE",
	"assertions": [] } ],
	"activeMaterialKeywords": [ { "label": "Ceramic",
	"synonyms": [],
	"occurrence": 14551,
	"urlNamespace": "browse/material-type",
	"slug": "ceramic",
	"dedupable": true,
	"detailUrl": "/browse/material-type/1/ceramic",
	"synonymFormattedName": "Ceramic",
	"id": 1,
	"status": "ACTIVE",
	"approved": true,
	"assertions": [] },
	{ "label": "Chipped Stone",
	"synonyms": [],
	"occurrence": 21291,
	"urlNamespace": "browse/material-type",
	"slug": "chipped-stone",
	"dedupable": true,
	"detailUrl": "/browse/material-type/2/chipped-stone",
	"synonymFormattedName": "Chipped Stone",
	"id": 2,
	"status": "ACTIVE",
	"approved": true,
	"assertions": [] } ],
	"activeOtherKeywords": [ { "label": "Pinellas Points",
	"synonyms": [],
	"occurrence": 19,
	"urlNamespace": "browse/other-keyword",
	"slug": "pinellas-points",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48781/pinellas-points",
	"synonymFormattedName": "Pinellas Points",
	"id": 48781,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "3 Sites Found",
	"synonyms": [],
	"occurrence": 42,
	"urlNamespace": "browse/other-keyword",
	"slug": "3-sites-found",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48782/3-sites-found",
	"synonymFormattedName": "3 Sites Found",
	"id": 48782,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Westo Shaped Points",
	"synonyms": [],
	"occurrence": 1,
	"urlNamespace": "browse/other-keyword",
	"slug": "westo-shaped-points",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48783/westo-shaped-points",
	"synonymFormattedName": "Westo Shaped Points",
	"id": 48783,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Florida Dahrm Number 845",
	"synonyms": [],
	"occurrence": 1,
	"urlNamespace": "browse/other-keyword",
	"slug": "florida-dahrm-number-845",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48784/florida-dahrm-number-845",
	"synonymFormattedName": "Florida Dahrm Number 845",
	"id": 48784,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Field Reconnaissance--Intensive",
	"synonyms": [],
	"occurrence": 349,
	"urlNamespace": "browse/other-keyword",
	"slug": "field-reconnaissance-intensive",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/10161/field-reconnaissance-intensive",
	"synonymFormattedName": "Field Reconnaissance--Intensive",
	"id": 10161,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Data Recovery",
	"synonyms": [],
	"occurrence": 790,
	"urlNamespace": "browse/other-keyword",
	"slug": "data-recovery",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/787/data-recovery",
	"synonymFormattedName": "Data Recovery",
	"id": 787,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Habitation",
	"synonyms": [],
	"occurrence": 392,
	"urlNamespace": "browse/other-keyword",
	"slug": "habitation",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/2291/habitation",
	"synonymFormattedName": "Habitation",
	"id": 2291,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Lithic Scatter",
	"synonyms": [ { "label": "Lithic Scatters",
	"synonyms": [],
	"occurrence": 1951,
	"urlNamespace": "browse/other-keyword",
	"slug": "lithic-scatters",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/608/lithic-scatters",
	"synonymFormattedName": "Lithic Scatters",
	"id": 608,
	"status": "ACTIVE",
	"assertions": [] } ],
	"occurrence": 5519,
	"urlNamespace": "browse/other-keyword",
	"slug": "lithic-scatter",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/565/lithic-scatter",
	"synonymFormattedName": "Lithic Scatter",
	"id": 565,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Survey",
	"synonyms": [ { "label": "Surveys",
	"synonyms": [],
	"occurrence": 0,
	"urlNamespace": "browse/other-keyword",
	"slug": "surveys",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/55948/surveys",
	"synonymFormattedName": "Surveys",
	"id": 55948,
	"status": "DUPLICATE",
	"assertions": [] } ],
	"occurrence": 7328,
	"urlNamespace": "browse/other-keyword",
	"slug": "survey",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/8857/survey",
	"synonymFormattedName": "Survey",
	"id": 8857,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Significance / Management",
	"synonyms": [],
	"occurrence": 21679,
	"urlNamespace": "browse/other-keyword",
	"slug": "significance-management",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/1152/significance-management",
	"synonymFormattedName": "Significance / Management",
	"id": 1152,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Cultural Resource Overview / Synthesis-Project",
	"synonyms": [],
	"occurrence": 2296,
	"urlNamespace": "browse/other-keyword",
	"slug": "cultural-resource-overview-synthesis-project",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/7204/cultural-resource-overview-synthesis-project",
	"synonymFormattedName": "Cultural Resource Overview / Synthesis-Project",
	"id": 7204,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Miller",
	"synonyms": [],
	"occurrence": 946,
	"urlNamespace": "browse/other-keyword",
	"slug": "miller",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48713/miller",
	"synonymFormattedName": "Miller",
	"id": 48713,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Prairie Cord Marked Sherd",
	"synonyms": [],
	"occurrence": 4,
	"urlNamespace": "browse/other-keyword",
	"slug": "prairie-cord-marked-sherd",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48780/prairie-cord-marked-sherd",
	"synonymFormattedName": "Prairie Cord Marked Sherd",
	"id": 48780,
	"status": "ACTIVE",
	"assertions": [] } ],
	"activeGeographicKeywords": [ { "label": "Lake City",
	"synonyms": [],
	"occurrence": 23,
	"code": null,
	"urlNamespace": "browse/geographic-keyword",
	"slug": "lake-city",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/8959/lake-city",
	"synonymFormattedName": "Lake City",
	"id": 8959,
	"status": "ACTIVE",
	"level": "CITY",
	"assertions": [] },
	{ "label": "United States of America (Country)",
	"synonyms": [],
	"occurrence": 350451,
	"code": "USA",
	"urlNamespace": "browse/geographic-keyword",
	"slug": "united-states-of-america-country",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/384/united-states-of-america-country",
	"synonymFormattedName": "United States of America (Country)",
	"id": 384,
	"status": "ACTIVE",
	"level": "COUNTRY",
	"assertions": [] },
	{ "label": "Florida (State / Territory)",
	"synonyms": [],
	"occurrence": 9745,
	"code": "UY07",
	"urlNamespace": "browse/geographic-keyword",
	"slug": "florida-state-territory",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/2273/florida-state-territory",
	"synonymFormattedName": "Florida (State / Territory)",
	"id": 2273,
	"status": "ACTIVE",
	"level": "STATE",
	"assertions": [] },
	{ "label": "Columbia (County)",
	"synonyms": [],
	"occurrence": 423,
	"code": null,
	"urlNamespace": "browse/geographic-keyword",
	"slug": "columbia-county",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/8722/columbia-county",
	"synonymFormattedName": "Columbia (County)",
	"id": 8722,
	"status": "ACTIVE",
	"level": "COUNTY",
	"assertions": [] },
	{ "label": "12023 (Fips Code)",
	"synonyms": [],
	"occurrence": 128,
	"code": null,
	"urlNamespace": "browse/geographic-keyword",
	"slug": "12023-fips-code",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/23156/12023-fips-code",
	"synonymFormattedName": "12023 (Fips Code)",
	"id": 23156,
	"status": "ACTIVE",
	"level": "FIPS_CODE",
	"assertions": [] },
	{ "label": "North America (Continent)",
	"synonyms": [],
	"occurrence": 350390,
	"code": "NA",
	"urlNamespace": "browse/geographic-keyword",
	"slug": "north-america-continent",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/2890/north-america-continent",
	"synonymFormattedName": "North America (Continent)",
	"id": 2890,
	"status": "ACTIVE",
	"level": "CONTINENT",
	"assertions": [] } ],
	"activeSiteNameKeywords": [],
	"activeSiteTypeKeywords": [],
	"activeIndividualAndInstitutionalCredit": [ { "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 172,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": null,
	"url": null,
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"email": null,
	"creatorType": "INSTITUTION",
	"properName": "fDAHRM",
	"label": "fDAHRM",
	"title": "fDAHRM",
	"detailUrl": "/browse/creators/47359/fdahrm",
	"slug": "fdahrm",
	"synonymFormattedName": "fDAHRM",
	"institutionName": null,
	"urlNamespace": "browse/creators",
	"id": 47359,
	"status": "ACTIVE",
	"name": "fDAHRM",
	"parentRef": null,
	"synonyms": [],
	"institution": {} },
	"id": 284958,
	"sequenceNumber": 2,
	"role": "SPONSOR" },
	{ "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 19928,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": "",
	"url": "",
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"email": null,
	"creatorType": "INSTITUTION",
	"properName": "State, County, and Local Government",
	"label": "State, County, and Local Government",
	"title": "State, County, and Local Government",
	"detailUrl": "/browse/creators/12729/state-county-and-local-government",
	"slug": "state-county-and-local-government",
	"synonymFormattedName": "State, County, and Local Government",
	"institutionName": null,
	"urlNamespace": "browse/creators",
	"id": 12729,
	"status": "ACTIVE",
	"name": "State, County, and Local Government",
	"parentRef": null,
	"synonyms": [],
	"institution": {} },
	"id": 284960,
	"sequenceNumber": 1,
	"role": "SPONSOR" } ],
	"activeResourceNotes": [ { "note": "Submitted to: FDAHRM",
	"id": 119737,
	"sequenceNumber": 0,
	"type": "GENERAL" } ],
	"activeCoverageDates": [],
	"activeRelatedComparativeCollections": [],
	"activeSourceCollections": [],
	"approvedMaterialKeywords": [ { "label": "Ceramic",
	"synonyms": [],
	"occurrence": 14551,
	"urlNamespace": "browse/material-type",
	"slug": "ceramic",
	"dedupable": true,
	"detailUrl": "/browse/material-type/1/ceramic",
	"synonymFormattedName": "Ceramic",
	"id": 1,
	"status": "ACTIVE",
	"approved": true,
	"assertions": [] },
	{ "label": "Chipped Stone",
	"synonyms": [],
	"occurrence": 21291,
	"urlNamespace": "browse/material-type",
	"slug": "chipped-stone",
	"dedupable": true,
	"detailUrl": "/browse/material-type/2/chipped-stone",
	"synonymFormattedName": "Chipped Stone",
	"id": 2,
	"status": "ACTIVE",
	"approved": true,
	"assertions": [] } ],
	"joinedInvestigationTypes": "Data Recovery / Excavation, Site Evaluation / Testing",
	"joinedCultureKeywords": "Leon Jefferson Period, Alachua Period, Lochloosa Punctated Sherd",
	"joinedMaterialKeywords": "Ceramic, Chipped Stone",
	"joinedOtherKeywords": "Pinellas Points, 3 Sites Found, Westo Shaped Points, Florida Dahrm Number 845, Field Reconnaissance--Intensive, Data Recovery, Habitation, Lithic Scatter, Survey, Significance / Management, Cultural Resource Overview / Synthesis-Project, Miller, Prairie Cord Marked Sherd",
	"joinedSiteNameKeywords": "",
	"joinedSiteTypeKeywords": "",
	"indexedGeographicKeywords": [ { "label": "Lake City",
	"synonyms": [],
	"occurrence": 23,
	"code": null,
	"urlNamespace": "browse/geographic-keyword",
	"slug": "lake-city",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/8959/lake-city",
	"synonymFormattedName": "Lake City",
	"id": 8959,
	"status": "ACTIVE",
	"level": "CITY",
	"assertions": [] },
	{ "label": "United States of America (Country)",
	"synonyms": [],
	"occurrence": 350451,
	"code": "USA",
	"urlNamespace": "browse/geographic-keyword",
	"slug": "united-states-of-america-country",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/384/united-states-of-america-country",
	"synonymFormattedName": "United States of America (Country)",
	"id": 384,
	"status": "ACTIVE",
	"level": "COUNTRY",
	"assertions": [] },
	{ "label": "Florida (State / Territory)",
	"synonyms": [],
	"occurrence": 9745,
	"code": "UY07",
	"urlNamespace": "browse/geographic-keyword",
	"slug": "florida-state-territory",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/2273/florida-state-territory",
	"synonymFormattedName": "Florida (State / Territory)",
	"id": 2273,
	"status": "ACTIVE",
	"level": "STATE",
	"assertions": [] },
	{ "label": "Columbia (County)",
	"synonyms": [],
	"occurrence": 423,
	"code": null,
	"urlNamespace": "browse/geographic-keyword",
	"slug": "columbia-county",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/8722/columbia-county",
	"synonymFormattedName": "Columbia (County)",
	"id": 8722,
	"status": "ACTIVE",
	"level": "COUNTY",
	"assertions": [] },
	{ "label": "12023 (Fips Code)",
	"synonyms": [],
	"occurrence": 128,
	"code": null,
	"urlNamespace": "browse/geographic-keyword",
	"slug": "12023-fips-code",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/23156/12023-fips-code",
	"synonymFormattedName": "12023 (Fips Code)",
	"id": 23156,
	"status": "ACTIVE",
	"level": "FIPS_CODE",
	"assertions": [] },
	{ "label": "North America (Continent)",
	"synonyms": [],
	"occurrence": 350390,
	"code": "NA",
	"urlNamespace": "browse/geographic-keyword",
	"slug": "north-america-continent",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/2890/north-america-continent",
	"synonymFormattedName": "North America (Continent)",
	"id": 2890,
	"status": "ACTIVE",
	"level": "CONTINENT",
	"assertions": [] } ],
	"joinedGeographicKeywords": "Lake City, United States of America (Country), Florida (State / Territory), Columbia (County), 12023 (Fips Code), North America (Continent)",
	"joinedManagedGeographicKeywords": "",
	"joinedTemporalKeywords": "Protohistoric Period, 1499-1000 A.D.",
	"resourceTypeLabel": "Document",
	"containsActiveKeywords": true,
	"individualAndInstitutionalCredit": [ { "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 172,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": null,
	"url": null,
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"email": null,
	"creatorType": "INSTITUTION",
	"properName": "fDAHRM",
	"label": "fDAHRM",
	"title": "fDAHRM",
	"detailUrl": "/browse/creators/47359/fdahrm",
	"slug": "fdahrm",
	"synonymFormattedName": "fDAHRM",
	"institutionName": null,
	"urlNamespace": "browse/creators",
	"id": 47359,
	"status": "ACTIVE",
	"name": "fDAHRM",
	"parentRef": null,
	"synonyms": [] },
	"id": 284958,
	"sequenceNumber": 2,
	"role": "SPONSOR" },
	{ "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 19928,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": "",
	"url": "",
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"email": null,
	"creatorType": "INSTITUTION",
	"properName": "State, County, and Local Government",
	"label": "State, County, and Local Government",
	"title": "State, County, and Local Government",
	"detailUrl": "/browse/creators/12729/state-county-and-local-government",
	"slug": "state-county-and-local-government",
	"synonymFormattedName": "State, County, and Local Government",
	"institutionName": null,
	"urlNamespace": "browse/creators",
	"id": 12729,
	"status": "ACTIVE",
	"name": "State, County, and Local Government",
	"parentRef": null,
	"synonyms": [] },
	"id": 284960,
	"sequenceNumber": 1,
	"role": "SPONSOR" } ],
	"detailUrl": "/document/107140/201-survey-and-test-excavations-lake-city-florida-testing-a-site-complex-at-alligator-lake",
	"slug": "201-survey-and-test-excavations-lake-city-florida-testing-a-site-complex-at-alligator-lake",
	"visibleUnmanagedResourceCollections": [],
	"firstLatitudeLongitudeBox": { "obfuscatedSouth": 29.825592041015625,
	"obfuscatedWest": -82.80048370361328,
	"obfuscatedNorth": 30.597740173339844,
	"obfuscatedEast": -82.4525146484375,
	"south": 29.825592041015625,
	"north": 30.597740173339844,
	"west": -82.80048370361328,
	"east": -82.4525146484375,
	"geographicKeywords": null,
	"initialized": true,
	"centerLatitudeIfNotObfuscated": 30.211666107177734,
	"centerLongitudeIfNotObfuscated": -82.62649917602539,
	"obfuscatedCenterLatitude": 30.211666107177734,
	"obfuscatedCenterLongitude": -82.62649917602539,
	"centerLatitude": 30.211666107177734,
	"centerLongitude": -82.62649917602539,
	"obfuscatedArea": 0.2686836560606025,
	"obfuscatedAbsoluteLatLength": 0.7721481323242188,
	"obfuscatedAbsoluteLongLength": 0.34796905517578125,
	"absoluteLatLength": 0.7721481323242188,
	"absoluteLongLength": 0.34796905517578125,
	"maximumLatitude": 30.597740173339844,
	"minimumLatitude": 29.825592041015625,
	"maximumLongitude": -82.4525146484375,
	"minimumLongitude": -82.80048370361328,
	"initializedAndValid": true,
	"area": 0.2686836560606025,
	"id": 426990,
	"okayToShowExactLocation": false },
	"uncontrolledCultureKeywords": [ { "label": "Leon Jefferson Period",
	"synonyms": [],
	"occurrence": 5,
	"urlNamespace": "browse/culture-keyword",
	"slug": "leon-jefferson-period",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2848/leon-jefferson-period",
	"synonymFormattedName": "Leon Jefferson Period",
	"id": 2848,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] },
	{ "label": "Alachua Period",
	"synonyms": [],
	"occurrence": 8,
	"urlNamespace": "browse/culture-keyword",
	"slug": "alachua-period",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2849/alachua-period",
	"synonymFormattedName": "Alachua Period",
	"id": 2849,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] },
	{ "label": "Lochloosa Punctated Sherd",
	"synonyms": [],
	"occurrence": 2,
	"urlNamespace": "browse/culture-keyword",
	"slug": "lochloosa-punctated-sherd",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2850/lochloosa-punctated-sherd",
	"synonymFormattedName": "Lochloosa Punctated Sherd",
	"id": 2850,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] } ],
	"uncontrolledMaterialKeywords": [],
	"uncontrolledSiteTypeKeywords": [],
	"urlNamespace": "document",
	"approvedCultureKeywords": [],
	"approvedSiteTypeKeywords": [],
	"primaryCreators": [ { "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 72,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": null,
	"url": null,
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"lastName": "Chance",
	"firstName": "Marsha A.",
	"orcidId": null,
	"email": null,
	"emailPublic": false,
	"institution": null,
	"rpaNumber": null,
	"phone": null,
	"phonePublic": false,
	"registered": false,
	"creatorType": "PERSON",
	"properName": "Marsha A. Chance",
	"label": "Chance, Marsha A.",
	"title": "Marsha A. Chance",
	"detailUrl": "/browse/creators/47360/marsha-a-chance",
	"slug": "marsha-a-chance",
	"synonymFormattedName": "Marsha A. Chance",
	"urlNamespace": "browse/creators",
	"id": 47360,
	"status": "ACTIVE",
	"synonyms": [] },
	"id": 284959,
	"sequenceNumber": 0,
	"role": "AUTHOR" } ],
	"id": 107140,
	"status": "ACTIVE",
	"submitterRef": "TdarUser:135028",
	"uploaderRef": "TdarUser:135028",
	"updaterRef": "TdarUser:8344",
	"projectRef": ":-1",
	"licenseType": null,
	"licenseText": null,
	"copyrightHolderRef": null,
	"resourceCollections": [ { "resourceCollectionRef": { "id": 31020 } } ],
	"resourceCreators": [ { "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 72,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": null,
	"url": null,
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"lastName": "Chance",
	"firstName": "Marsha A.",
	"orcidId": null,
	"email": null,
	"emailPublic": false,
	"institution": null,
	"rpaNumber": null,
	"phone": null,
	"phonePublic": false,
	"registered": false,
	"creatorType": "PERSON",
	"properName": "Marsha A. Chance",
	"label": "Chance, Marsha A.",
	"title": "Marsha A. Chance",
	"detailUrl": "/browse/creators/47360/marsha-a-chance",
	"slug": "marsha-a-chance",
	"synonymFormattedName": "Marsha A. Chance",
	"urlNamespace": "browse/creators",
	"id": 47360,
	"status": "ACTIVE",
	"synonyms": [] },
	"id": 284959,
	"sequenceNumber": 0,
	"role": "AUTHOR" },
	{ "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 19928,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": "",
	"url": "",
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"email": null,
	"creatorType": "INSTITUTION",
	"properName": "State, County, and Local Government",
	"label": "State, County, and Local Government",
	"title": "State, County, and Local Government",
	"detailUrl": "/browse/creators/12729/state-county-and-local-government",
	"slug": "state-county-and-local-government",
	"synonymFormattedName": "State, County, and Local Government",
	"institutionName": null,
	"urlNamespace": "browse/creators",
	"id": 12729,
	"status": "ACTIVE",
	"name": "State, County, and Local Government",
	"parentRef": null,
	"synonyms": [] },
	"id": 284960,
	"sequenceNumber": 1,
	"role": "SPONSOR" },
	{ "creator": { "obfuscatedObjectDifferent": null,
	"occurrence": 172,
	"dateCreated": "2015-10-30T17:22:26-07:00",
	"description": null,
	"url": null,
	"addresses": [],
	"maxHeight": null,
	"maxWidth": null,
	"maxSize": null,
	"email": null,
	"creatorType": "INSTITUTION",
	"properName": "fDAHRM",
	"label": "fDAHRM",
	"title": "fDAHRM",
	"detailUrl": "/browse/creators/47359/fdahrm",
	"slug": "fdahrm",
	"synonymFormattedName": "fDAHRM",
	"institutionName": null,
	"urlNamespace": "browse/creators",
	"id": 47359,
	"status": "ACTIVE",
	"name": "fDAHRM",
	"parentRef": null,
	"synonyms": [] },
	"id": 284958,
	"sequenceNumber": 2,
	"role": "SPONSOR" } ],
	"resourceNotes": [ { "note": "Submitted to: FDAHRM",
	"id": 119737,
	"sequenceNumber": 0,
	"type": "GENERAL" } ],
	"resourceAnnotations": [ { "resourceAnnotationKey": { "key": "NADB citation id number",
	"formatString": null,
	"id": 18,
	"resourceAnnotationType": "IDENTIFIER",
	"annotationDataType": null },
	"value": "000000048310",
	"pairedValue": "NADB citation id number:000000048310",
	"id": 866844 },
	{ "resourceAnnotationKey": { "key": "NADB document id number",
	"formatString": null,
	"id": 19,
	"resourceAnnotationType": "IDENTIFIER",
	"annotationDataType": null },
	"value": "353565",
	"pairedValue": "NADB document id number:353565",
	"id": 866843 } ],
	"sourceCollections": [],
	"relatedComparativeCollections": [],
	"latitudeLongitudeBoxes": [ { "obfuscatedSouth": 29.825592041015625,
	"obfuscatedWest": -82.80048370361328,
	"obfuscatedNorth": 30.597740173339844,
	"obfuscatedEast": -82.4525146484375,
	"south": 29.825592041015625,
	"north": 30.597740173339844,
	"west": -82.80048370361328,
	"east": -82.4525146484375,
	"geographicKeywords": null,
	"initialized": true,
	"centerLatitudeIfNotObfuscated": 30.211666107177734,
	"centerLongitudeIfNotObfuscated": -82.62649917602539,
	"obfuscatedCenterLatitude": 30.211666107177734,
	"obfuscatedCenterLongitude": -82.62649917602539,
	"centerLatitude": 30.211666107177734,
	"centerLongitude": -82.62649917602539,
	"obfuscatedArea": 0.2686836560606025,
	"obfuscatedAbsoluteLatLength": 0.7721481323242188,
	"obfuscatedAbsoluteLongLength": 0.34796905517578125,
	"absoluteLatLength": 0.7721481323242188,
	"absoluteLongLength": 0.34796905517578125,
	"maximumLatitude": 30.597740173339844,
	"minimumLatitude": 29.825592041015625,
	"maximumLongitude": -82.4525146484375,
	"minimumLongitude": -82.80048370361328,
	"initializedAndValid": true,
	"area": 0.2686836560606025,
	"id": 426990,
	"okayToShowExactLocation": false } ],
	"geographicKeywords": [ { "label": "Lake City",
	"synonyms": [],
	"occurrence": 23,
	"code": null,
	"urlNamespace": "browse/geographic-keyword",
	"slug": "lake-city",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/8959/lake-city",
	"synonymFormattedName": "Lake City",
	"id": 8959,
	"status": "ACTIVE",
	"level": "CITY",
	"assertions": [] },
	{ "label": "United States of America (Country)",
	"synonyms": [],
	"occurrence": 350451,
	"code": "USA",
	"urlNamespace": "browse/geographic-keyword",
	"slug": "united-states-of-america-country",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/384/united-states-of-america-country",
	"synonymFormattedName": "United States of America (Country)",
	"id": 384,
	"status": "ACTIVE",
	"level": "COUNTRY",
	"assertions": [] },
	{ "label": "Florida (State / Territory)",
	"synonyms": [],
	"occurrence": 9745,
	"code": "UY07",
	"urlNamespace": "browse/geographic-keyword",
	"slug": "florida-state-territory",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/2273/florida-state-territory",
	"synonymFormattedName": "Florida (State / Territory)",
	"id": 2273,
	"status": "ACTIVE",
	"level": "STATE",
	"assertions": [] },
	{ "label": "Columbia (County)",
	"synonyms": [],
	"occurrence": 423,
	"code": null,
	"urlNamespace": "browse/geographic-keyword",
	"slug": "columbia-county",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/8722/columbia-county",
	"synonymFormattedName": "Columbia (County)",
	"id": 8722,
	"status": "ACTIVE",
	"level": "COUNTY",
	"assertions": [] },
	{ "label": "12023 (Fips Code)",
	"synonyms": [],
	"occurrence": 128,
	"code": null,
	"urlNamespace": "browse/geographic-keyword",
	"slug": "12023-fips-code",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/23156/12023-fips-code",
	"synonymFormattedName": "12023 (Fips Code)",
	"id": 23156,
	"status": "ACTIVE",
	"level": "FIPS_CODE",
	"assertions": [] },
	{ "label": "North America (Continent)",
	"synonyms": [],
	"occurrence": 350390,
	"code": "NA",
	"urlNamespace": "browse/geographic-keyword",
	"slug": "north-america-continent",
	"dedupable": true,
	"detailUrl": "/browse/geographic-keyword/2890/north-america-continent",
	"synonymFormattedName": "North America (Continent)",
	"id": 2890,
	"status": "ACTIVE",
	"level": "CONTINENT",
	"assertions": [] } ],
	"managedGeographicKeywords": [],
	"temporalKeywords": [ { "label": "Protohistoric Period",
	"synonyms": [],
	"occurrence": 70,
	"urlNamespace": "browse/temporal-keyword",
	"slug": "protohistoric-period",
	"dedupable": true,
	"detailUrl": "/browse/temporal-keyword/161/protohistoric-period",
	"synonymFormattedName": "Protohistoric Period",
	"id": 161,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "1499-1000 A.D.",
	"synonyms": [],
	"occurrence": 3,
	"urlNamespace": "browse/temporal-keyword",
	"slug": "1499-1000-ad",
	"dedupable": true,
	"detailUrl": "/browse/temporal-keyword/839/1499-1000-ad",
	"synonymFormattedName": "1499-1000 A.D.",
	"id": 839,
	"status": "ACTIVE",
	"assertions": [] } ],
	"coverageDates": [],
	"cultureKeywords": [ { "label": "Leon Jefferson Period",
	"synonyms": [],
	"occurrence": 5,
	"urlNamespace": "browse/culture-keyword",
	"slug": "leon-jefferson-period",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2848/leon-jefferson-period",
	"synonymFormattedName": "Leon Jefferson Period",
	"id": 2848,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] },
	{ "label": "Alachua Period",
	"synonyms": [],
	"occurrence": 8,
	"urlNamespace": "browse/culture-keyword",
	"slug": "alachua-period",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2849/alachua-period",
	"synonymFormattedName": "Alachua Period",
	"id": 2849,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] },
	{ "label": "Lochloosa Punctated Sherd",
	"synonyms": [],
	"occurrence": 2,
	"urlNamespace": "browse/culture-keyword",
	"slug": "lochloosa-punctated-sherd",
	"dedupable": true,
	"detailUrl": "/browse/culture-keyword/2850/lochloosa-punctated-sherd",
	"synonymFormattedName": "Lochloosa Punctated Sherd",
	"id": 2850,
	"status": "ACTIVE",
	"selectable": false,
	"index": null,
	"parentRef": null,
	"approved": false,
	"assertions": [] } ],
	"otherKeywords": [ { "label": "Pinellas Points",
	"synonyms": [],
	"occurrence": 19,
	"urlNamespace": "browse/other-keyword",
	"slug": "pinellas-points",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48781/pinellas-points",
	"synonymFormattedName": "Pinellas Points",
	"id": 48781,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "3 Sites Found",
	"synonyms": [],
	"occurrence": 42,
	"urlNamespace": "browse/other-keyword",
	"slug": "3-sites-found",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48782/3-sites-found",
	"synonymFormattedName": "3 Sites Found",
	"id": 48782,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Westo Shaped Points",
	"synonyms": [],
	"occurrence": 1,
	"urlNamespace": "browse/other-keyword",
	"slug": "westo-shaped-points",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48783/westo-shaped-points",
	"synonymFormattedName": "Westo Shaped Points",
	"id": 48783,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Florida Dahrm Number 845",
	"synonyms": [],
	"occurrence": 1,
	"urlNamespace": "browse/other-keyword",
	"slug": "florida-dahrm-number-845",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48784/florida-dahrm-number-845",
	"synonymFormattedName": "Florida Dahrm Number 845",
	"id": 48784,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Field Reconnaissance--Intensive",
	"synonyms": [],
	"occurrence": 349,
	"urlNamespace": "browse/other-keyword",
	"slug": "field-reconnaissance-intensive",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/10161/field-reconnaissance-intensive",
	"synonymFormattedName": "Field Reconnaissance--Intensive",
	"id": 10161,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Data Recovery",
	"synonyms": [],
	"occurrence": 790,
	"urlNamespace": "browse/other-keyword",
	"slug": "data-recovery",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/787/data-recovery",
	"synonymFormattedName": "Data Recovery",
	"id": 787,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Habitation",
	"synonyms": [],
	"occurrence": 392,
	"urlNamespace": "browse/other-keyword",
	"slug": "habitation",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/2291/habitation",
	"synonymFormattedName": "Habitation",
	"id": 2291,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Lithic Scatter",
	"synonyms": [ { "label": "Lithic Scatters",
	"synonyms": [],
	"occurrence": 1951,
	"urlNamespace": "browse/other-keyword",
	"slug": "lithic-scatters",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/608/lithic-scatters",
	"synonymFormattedName": "Lithic Scatters",
	"id": 608,
	"status": "ACTIVE",
	"assertions": [] } ],
	"occurrence": 5519,
	"urlNamespace": "browse/other-keyword",
	"slug": "lithic-scatter",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/565/lithic-scatter",
	"synonymFormattedName": "Lithic Scatter",
	"id": 565,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Survey",
	"synonyms": [ { "label": "Surveys",
	"synonyms": [],
	"occurrence": 0,
	"urlNamespace": "browse/other-keyword",
	"slug": "surveys",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/55948/surveys",
	"synonymFormattedName": "Surveys",
	"id": 55948,
	"status": "DUPLICATE",
	"assertions": [] } ],
	"occurrence": 7328,
	"urlNamespace": "browse/other-keyword",
	"slug": "survey",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/8857/survey",
	"synonymFormattedName": "Survey",
	"id": 8857,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Significance / Management",
	"synonyms": [],
	"occurrence": 21679,
	"urlNamespace": "browse/other-keyword",
	"slug": "significance-management",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/1152/significance-management",
	"synonymFormattedName": "Significance / Management",
	"id": 1152,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Cultural Resource Overview / Synthesis-Project",
	"synonyms": [],
	"occurrence": 2296,
	"urlNamespace": "browse/other-keyword",
	"slug": "cultural-resource-overview-synthesis-project",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/7204/cultural-resource-overview-synthesis-project",
	"synonymFormattedName": "Cultural Resource Overview / Synthesis-Project",
	"id": 7204,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Miller",
	"synonyms": [],
	"occurrence": 946,
	"urlNamespace": "browse/other-keyword",
	"slug": "miller",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48713/miller",
	"synonymFormattedName": "Miller",
	"id": 48713,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Prairie Cord Marked Sherd",
	"synonyms": [],
	"occurrence": 4,
	"urlNamespace": "browse/other-keyword",
	"slug": "prairie-cord-marked-sherd",
	"dedupable": true,
	"detailUrl": "/browse/other-keyword/48780/prairie-cord-marked-sherd",
	"synonymFormattedName": "Prairie Cord Marked Sherd",
	"id": 48780,
	"status": "ACTIVE",
	"assertions": [] } ],
	"siteNameKeywords": [],
	"materialKeywords": [ { "label": "Ceramic",
	"synonyms": [],
	"occurrence": 14551,
	"urlNamespace": "browse/material-type",
	"slug": "ceramic",
	"dedupable": true,
	"detailUrl": "/browse/material-type/1/ceramic",
	"synonymFormattedName": "Ceramic",
	"id": 1,
	"status": "ACTIVE",
	"approved": true,
	"assertions": [] },
	{ "label": "Chipped Stone",
	"synonyms": [],
	"occurrence": 21291,
	"urlNamespace": "browse/material-type",
	"slug": "chipped-stone",
	"dedupable": true,
	"detailUrl": "/browse/material-type/2/chipped-stone",
	"synonymFormattedName": "Chipped Stone",
	"id": 2,
	"status": "ACTIVE",
	"approved": true,
	"assertions": [] } ],
	"investigationTypes": [ { "label": "Site Evaluation / Testing",
	"synonyms": [],
	"occurrence": 96489,
	"urlNamespace": "browse/investigation-type",
	"slug": "site-evaluation-testing",
	"dedupable": true,
	"detailUrl": "/browse/investigation-type/10/site-evaluation-testing",
	"synonymFormattedName": "Site Evaluation / Testing",
	"id": 10,
	"status": "ACTIVE",
	"assertions": [] },
	{ "label": "Data Recovery / Excavation",
	"synonyms": [],
	"occurrence": 14626,
	"urlNamespace": "browse/investigation-type",
	"slug": "data-recovery-excavation",
	"dedupable": true,
	"detailUrl": "/browse/investigation-type/5/data-recovery-excavation",
	"synonymFormattedName": "Data Recovery / Excavation",
	"id": 5,
	"status": "ACTIVE",
	"assertions": [] } ],
	"siteTypeKeywords": [],
	"authorizedUsers": [ { "generalPermission": "MODIFY_RECORD",
	"effectiveGeneralPermission": 500,
	"dateCreated": "2017-07-21T17:24:39-07:00",
	"dateExpires": null,
	"collectionId": null,
	"resourceId": 107140,
	"enabled": false,
	"id": 96977,
	"personRef": "TdarUser:135028",
	"createdByRef": "TdarUser:135028" } ],
	"informationResourceFiles": [ { "transientDownloadCount": null,
	"description": "",
	"fileCreatedDate": null,
	"partOfComposite": false,
	"deleted": false,
	"informationResourceFileType": "DOCUMENT",
	"numberOfParts": 13,
	"preservationNote": null,
	"filename": "MobileNav.pdf",
	"restriction": "PUBLIC",
	"errorMessage": null,
	"dateMadePublic": null,
	"status": "PROCESSED",
	"viewable": false,
	"zoomableVersion": { "transientFile": null,
	"filename": "MobileNav1_lg.jpg",
	"mimeType": "image/jpeg",
	"format": null,
	"primaryFile": false,
	"extension": "jpg",
	"premisId": null,
	"filestoreId": null,
	"checksum": "23022f2de5815611d5780571495d4a20",
	"checksumType": "MD5",
	"dateCreated": "2018-09-05T17:38:07-07:00",
	"fileType": null,
	"fileVersionType": "WEB_LARGE",
	"width": 319,
	"height": 600,
	"totalTime": null,
	"fileLength": 18698,
	"uncompressedSizeOnDisk": 4593600,
	"path": "resource/10/71/40/rec/109082/v1/deriv",
	"type": "RESOURCE",
	"persistableId": 107140,
	"versionType": "WEB_LARGE",
	"derivative": true,
	"indexable": false,
	"id": 528171,
	"version": 1,
	"informationResourceFileId": 109082 },
	"columnarDataFileType": false,
	"embargoed": false,
	"hasTranslatedVersion": false,
	"id": 109082,
	"sequenceNumber": 0,
	"informationResourceRef": "Document:107140",
	"latestVersion": 1,
	"informationResourceFileVersions": [ { "transientFile": null,
	"filename": "MobileNav.pdf",
	"mimeType": "application/pdf",
	"format": null,
	"primaryFile": false,
	"extension": "pdf",
	"premisId": null,
	"filestoreId": null,
	"checksum": "df9666d30e99be7c49ca178b9410d190",
	"checksumType": "MD5",
	"dateCreated": "2018-09-05T17:38:02-07:00",
	"fileType": null,
	"fileVersionType": "UPLOADED",
	"width": null,
	"height": null,
	"totalTime": null,
	"fileLength": 8840276,
	"uncompressedSizeOnDisk": 8840276,
	"path": "resource/10/71/40/rec/109082/v1",
	"type": "RESOURCE",
	"persistableId": 107140,
	"versionType": "UPLOADED",
	"derivative": false,
	"indexable": false,
	"id": 528168,
	"version": 1,
	"informationResourceFileId": 109082 },
	{ "transientFile": null,
	"filename": "MobileNav.pdf.index.txt",
	"mimeType": "text/plain",
	"format": null,
	"primaryFile": false,
	"extension": "txt",
	"premisId": null,
	"filestoreId": null,
	"checksum": "2e1ce3af0dd6519778b3dab32d091cae",
	"checksumType": "MD5",
	"dateCreated": "2018-09-05T17:38:04-07:00",
	"fileType": null,
	"fileVersionType": "INDEXABLE_TEXT",
	"width": null,
	"height": null,
	"totalTime": null,
	"fileLength": 126,
	"uncompressedSizeOnDisk": 126,
	"path": "resource/10/71/40/rec/109082/v1/deriv",
	"type": "RESOURCE",
	"persistableId": 107140,
	"versionType": "INDEXABLE_TEXT",
	"derivative": true,
	"indexable": true,
	"id": 528169,
	"version": 1,
	"informationResourceFileId": 109082 },
	{ "transientFile": null,
	"filename": "MobileNav.pdf.metadata",
	"mimeType": "text/plain",
	"format": null,
	"primaryFile": false,
	"extension": "metadata",
	"premisId": null,
	"filestoreId": null,
	"checksum": "94f3bebea4fab4d0a26e3274a5c3a768",
	"checksumType": "MD5",
	"dateCreated": "2018-09-05T17:38:04-07:00",
	"fileType": null,
	"fileVersionType": "METADATA",
	"width": null,
	"height": null,
	"totalTime": null,
	"fileLength": 1250,
	"uncompressedSizeOnDisk": 1250,
	"path": "resource/10/71/40/rec/109082/v1/deriv",
	"type": "RESOURCE",
	"persistableId": 107140,
	"versionType": "METADATA",
	"derivative": true,
	"indexable": false,
	"id": 528170,
	"version": 1,
	"informationResourceFileId": 109082 },
	{ "transientFile": null,
	"filename": "MobileNav1_lg.jpg",
	"mimeType": "image/jpeg",
	"format": null,
	"primaryFile": false,
	"extension": "jpg",
	"premisId": null,
	"filestoreId": null,
	"checksum": "23022f2de5815611d5780571495d4a20",
	"checksumType": "MD5",
	"dateCreated": "2018-09-05T17:38:07-07:00",
	"fileType": null,
	"fileVersionType": "WEB_LARGE",
	"width": 319,
	"height": 600,
	"totalTime": null,
	"fileLength": 18698,
	"uncompressedSizeOnDisk": 4593600,
	"path": "resource/10/71/40/rec/109082/v1/deriv",
	"type": "RESOURCE",
	"persistableId": 107140,
	"versionType": "WEB_LARGE",
	"derivative": true,
	"indexable": false,
	"id": 528171,
	"version": 1,
	"informationResourceFileId": 109082 },
	{ "transientFile": null,
	"filename": "MobileNav1_md.jpg",
	"mimeType": "image/jpeg",
	"format": null,
	"primaryFile": false,
	"extension": "jpg",
	"premisId": null,
	"filestoreId": null,
	"checksum": "61eab4c0e743fff85469cceec2f370a5",
	"checksumType": "MD5",
	"dateCreated": "2018-09-05T17:38:07-07:00",
	"fileType": null,
	"fileVersionType": "WEB_MEDIUM",
	"width": 159,
	"height": 300,
	"totalTime": null,
	"fileLength": 7518,
	"uncompressedSizeOnDisk": 1144800,
	"path": "resource/10/71/40/rec/109082/v1/deriv",
	"type": "RESOURCE",
	"persistableId": 107140,
	"versionType": "WEB_MEDIUM",
	"derivative": true,
	"indexable": false,
	"id": 528172,
	"version": 1,
	"informationResourceFileId": 109082 },
	{ "transientFile": null,
	"filename": "MobileNav1_sm.jpg",
	"mimeType": "image/jpeg",
	"format": null,
	"primaryFile": false,
	"extension": "jpg",
	"premisId": null,
	"filestoreId": null,
	"checksum": "668c786f21f922b51a10af8ea64c7299",
	"checksumType": "MD5",
	"dateCreated": "2018-09-05T17:38:07-07:00",
	"fileType": null,
	"fileVersionType": "WEB_SMALL",
	"width": 51,
	"height": 96,
	"totalTime": null,
	"fileLength": 1425,
	"uncompressedSizeOnDisk": 117504,
	"path": "resource/10/71/40/rec/109082/v1/deriv",
	"type": "RESOURCE",
	"persistableId": 107140,
	"versionType": "WEB_SMALL",
	"derivative": true,
	"indexable": false,
	"id": 528173,
	"version": 1,
	"informationResourceFileId": 109082 } ] },
	{ "transientDownloadCount": null,
	"description": "",
	"fileCreatedDate": null,
	"partOfComposite": false,
	"deleted": false,
	"informationResourceFileType": "DOCUMENT",
	"numberOfParts": 0,
	"preservationNote": null,
	"filename": "Kohler et al PAGES draft 8-5-18_PIB.DOCX",
	"restriction": "PUBLIC",
	"errorMessage": null,
	"dateMadePublic": null,
	"status": "PROCESSED",
	"viewable": false,
	"zoomableVersion": null,
	"columnarDataFileType": false,
	"embargoed": false,
	"hasTranslatedVersion": false,
	"id": 109081,
	"sequenceNumber": 0,
	"informationResourceRef": "Document:107140",
	"latestVersion": 1,
	"informationResourceFileVersions": [ { "transientFile": null,
	"filename": "Kohler-et-al-PAGES-draft-8-5-18_PIB.DOCX",
	"mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	"format": null,
	"primaryFile": false,
	"extension": "DOCX",
	"premisId": null,
	"filestoreId": null,
	"checksum": "cfd834d78872a7a4dc174ec0675c5aaa",
	"checksumType": "MD5",
	"dateCreated": "2018-09-05T17:06:45-07:00",
	"fileType": null,
	"fileVersionType": "UPLOADED",
	"width": null,
	"height": null,
	"totalTime": null,
	"fileLength": 2430000,
	"uncompressedSizeOnDisk": 2430000,
	"path": "resource/10/71/40/rec/109081/v1",
	"type": "RESOURCE",
	"persistableId": 107140,
	"versionType": "UPLOADED",
	"derivative": false,
	"indexable": false,
	"id": 528165,
	"version": 1,
	"informationResourceFileId": 109081 },
	{ "transientFile": null,
	"filename": "Kohler-et-al-PAGES-draft-8-5-18_PIB.DOCX.index.txt",
	"mimeType": "text/plain",
	"format": null,
	"primaryFile": false,
	"extension": "txt",
	"premisId": null,
	"filestoreId": null,
	"checksum": "dd01807737917537e6cf24d8ccbcda49",
	"checksumType": "MD5",
	"dateCreated": "2018-09-05T17:06:47-07:00",
	"fileType": null,
	"fileVersionType": "INDEXABLE_TEXT",
	"width": null,
	"height": null,
	"totalTime": null,
	"fileLength": 14532,
	"uncompressedSizeOnDisk": 14532,
	"path": "resource/10/71/40/rec/109081/v1/deriv",
	"type": "RESOURCE",
	"persistableId": 107140,
	"versionType": "INDEXABLE_TEXT",
	"derivative": true,
	"indexable": true,
	"id": 528166,
	"version": 1,
	"informationResourceFileId": 109081 },
	{ "transientFile": null,
	"filename": "Kohler-et-al-PAGES-draft-8-5-18_PIB.DOCX.metadata",
	"mimeType": "text/plain",
	"format": null,
	"primaryFile": false,
	"extension": "metadata",
	"premisId": null,
	"filestoreId": null,
	"checksum": "7ea3650334883dfd463508a96ba4ee90",
	"checksumType": "MD5",
	"dateCreated": "2018-09-05T17:06:47-07:00",
	"fileType": null,
	"fileVersionType": "METADATA",
	"width": null,
	"height": null,
	"totalTime": null,
	"fileLength": 1388,
	"uncompressedSizeOnDisk": 1388,
	"path": "resource/10/71/40/rec/109081/v1/deriv",
	"type": "RESOURCE",
	"persistableId": 107140,
	"versionType": "METADATA",
	"derivative": true,
	"indexable": false,
	"id": 528167,
	"version": 1,
	"informationResourceFileId": 109081 } ] } ],
	"fileProxies": [],
	"contentOwners": [ { "creator": { "person": { "institution": {} },
	"institution": {} } } ],
	"controlledMaterialKeywords": [ { "label": "Ceramic",
	"synonyms": [],
	"occurrence": 14551,
	"urlNamespace": "browse/material-type",
	"slug": "ceramic",
	"dedupable": true,
	"detailUrl": "/browse/material-type/1/ceramic",
	"synonymFormattedName": "Ceramic",
	"id": 1,
	"status": "ACTIVE",
	"approved": true,
	"assertions": [] },
	{ "label": "Chipped Stone",
	"synonyms": [],
	"occurrence": 21291,
	"urlNamespace": "browse/material-type",
	"slug": "chipped-stone",
	"dedupable": true,
	"detailUrl": "/browse/material-type/2/chipped-stone",
	"synonymFormattedName": "Chipped Stone",
	"id": 2,
	"status": "ACTIVE",
	"approved": true,
	"assertions": [] } ] }


var expectedFields = [{"name":"accountId" },
{"name":"authorshipProxies[0].id"  , value:"284959"},
{"name":"authorshipProxies[0].institution.id"  , value:"-1"},
{"name":"authorshipProxies[0].institution.name" },
{"name":"authorshipProxies[0].person.email" },
{"name":"authorshipProxies[0].person.firstName"  , value:"Marsha A."},
{"name":"authorshipProxies[0].person.id"  , value:"47360"},
{"name":"authorshipProxies[0].person.institution.name" },
{"name":"authorshipProxies[0].person.lastName"  , value:"Chance"},
{"name":"authorshipProxies[0].role" },
{"name":"authorshipProxies[0].role" },
{"name":"authorshipProxies[0].type"  , value:"PERSON"},
{"name":"creditProxies[0].id"  , value:"284960"},
{"name":"creditProxies[0].type"  , value:"INSTITUTION"},
{"name":"document.bookTitle" },
{"name":"document.copyLocation"  , value:"FDAHRM, Tallahassee, Florida [164]"},
{"name":"document.date"  , value:"1982"},
{"name":"document.degree"  , value:"DOCTORAL"},
{"name":"document.degree"  , value:"MASTERS"},
{"name":"document.degree"  , value:"UNDERGRADUATE"},
{"name":"document.description" },
{"name":"document.documentType"  , value:"BOOK"},
{"name":"document.documentType"  , value:"BOOK_SECTION"},
{"name":"document.documentType"  , value:"CONFERENCE_PRESENTATION"},
{"name":"document.documentType"  , value:"JOURNAL_ARTICLE"},
{"name":"document.documentType"  , value:"OTHER"},
{"name":"document.documentType"  , value:"REPORT"},
{"name":"document.documentType"  , value:"THESIS"},
{"name":"document.doi" },
{"name":"document.edition" },
{"name":"document.endPage" },
{"name":"document.isbn" },
{"name":"document.issn" },
{"name":"document.journalName" },
{"name":"document.journalNumber" },
{"name":"document.publisherLocation" },
{"name":"document.seriesName" },
{"name":"document.seriesNumber" },
{"name":"document.startPage" },
{"name":"document.title"  , value:"201 Survey and Test Excavations, Lake City, Florida: Testing a Site Complex at Alligator Lake"},
{"name":"document.url" },
{"name":"document.volume" },
{"name":"doubleSubmitKey"  , value:"f10b126b-1e45-4f6e-8557-809f8ff6d472"},
{"name":"epochTimeUpdated"  , value:"1536194280006"},
{"name":"fileProxies[0].action"  , value:"NONE"},
{"name":"fileProxies[0].description" },
{"name":"fileProxies[0].fileCreatedDate" },
{"name":"fileProxies[0].fileId"  , value:"109082"},
{"name":"fileProxies[0].name"  , value:"MobileNav.pdf"},
{"name":"fileProxies[0].restriction" },
{"name":"fileProxies[0].tdarFileId"  , value:"-1"},
{"name":"fileProxies[1].action"  , value:"NONE"},
{"name":"fileProxies[1].description" },
{"name":"fileProxies[1].fileCreatedDate" },
{"name":"fileProxies[1].fileId"  , value:"109081"},
{"name":"fileProxies[1].name"  , value:"Kohler-et-al-PAGES-draft-8-5-18_PIB.DOCX"},
{"name":"fileProxies[1].restriction" },
{"name":"fileProxies[1].tdarFileId"  , value:"-1"},
{"name":"files[]" },
{"name":"id"  , value:"107140"},
{"name":"projectId" },
{"name":"publisherName" },
{"name":"replaceFile" },
{"name":"replaceFile" },
{"name":"resource.inheritingIndividualAndInstitutionalCredit"  , value:"true"},
{"name":"resourceLanguage" },
{"name":"resourceProviderInstitutionName" },
{"name":"sequenceNumberFieldName"  , value:"1"},
{"name":"sequenceNumberFieldName"  , value:"1"},
{"name":"shares[0].id"  , value:"31020"},
{"name":"shares[0].name"  , value:"National Archeological Database (NADB)"},
{"name":"startTime"  , value:"1537921754550"},
{"name":"status" },
{"name":"submitter.id"  , value:"135028"},
{"name":"submitterProperName"  , value:"system user"},
{"name":"ticketId" },
{"name":"vueFilesFallback" },
];

});