FROM local:maven

LABEL MAINTAINER=adam.brin@asu.edu

RUN apt-get update &&  apt-get install -y libapr1*  && \
  rm -rf /var/lib/apt/lists/* 

WORKDIR /opt
RUN mkdir -p /opt/tomcat/
RUN wget http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32.tar.gz ;
RUN tar -xvzf apache-tomcat-8.5.32.tar.gz -C /opt/tomcat/ --strip-components=1 ; chmod 755 /opt/tomcat/bin/* ; rm /opt/apache-tomcat-8.5.32.tar.gz ; rm -Rrf /opt/tomcat/webapps/examples ; rm -Rrf /opt/tomcat/webapps/docs ; rm -Rrf /opt/tomcat/webapps/ROOT  ; rm -Rrf /opt/tomcat/webapps/manager  ; rm -Rrf /opt/tomcat/webapps/host-manager

EXPOSE 8080
EXPOSE 8443
VOLUME /config
VOLUME /app
VOLUME /data

COPY tomcat-entrypoint.sh /usr/local/bin/
RUN ln -s usr/local/bin/tomcat-entrypoint.sh / # backwards compat
# ENTRYPOINT ["tomcat-entrypoint.sh"]

# USER tomcat
CMD ["/opt/tomcat/bin/catalina.sh","run"]
