FROM solr:latest

MAINTAINER Adam Brin <adam.brin@asu.edu>
ARG JTS_VERSION=1.15.0


RUN set -x \
  && curl -o /opt/solr/server/solr-webapp/webapp/WEB-INF/lib/jts-core-${JTS_VERSION}.jar https://repo1.maven.org/maven2/org/locationtech/jts/jts-core/${JTS_VERSION}/jts-core-${JTS_VERSION}.jar
  
RUN rm -Rrf  /opt/solr/server/solr/mycores && rm -Rrf /opt/solr/server/solr/mycores/gettingstarted