package org.tdar.core.service;

import java.io.File;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.WeakHashMap;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.tdar.core.bean.PersonalFilestoreTicket;
import org.tdar.core.bean.entity.TdarUser;
import org.tdar.core.dao.base.GenericDao;
import org.tdar.filestore.personal.BagitPersonalFilestore;
import org.tdar.filestore.personal.PersonalFileType;
import org.tdar.filestore.personal.PersonalFilestore;
import org.tdar.filestore.personal.PersonalFilestoreFile;

/**
 * Manages adding and saving files in the @link PersonalFilestore
 * 
 * @author <a href='jim.devos@asu.edu'>Jim Devos</a>, <a href='mailto:allen.lee@asu.edu'>Allen Lee</a>
 * @version $Rev$
 */
@Service
public class PersonalFilestoreService {

    @Autowired
    private GenericDao genericDao;

    // FIXME: double check that won't leak memory
    private Map<TdarUser, PersonalFilestore> personalFilestoreCache = new WeakHashMap<TdarUser, PersonalFilestore>();

    /**
     * Creates a new PersonalFilestoreTicket that the personal filestore can use to create a filestore in a unique location.
     * 
     * @return a new PersonalFilestoreTicket used to keep track of files uploaded by the given Person
     */
    @Transactional
    public PersonalFilestoreTicket createPersonalFilestoreTicket(TdarUser person) {
        return createPersonalFilestoreTicket(person, PersonalFileType.UPLOAD);
    }

    /**
     * Creates a new PersonalFilestoreTicket for the given Person with the given PersonalFileType (either UPLOAD or INTEGRATION)
     * 
     * @param person
     * @param fileType
     *            whether or not the ticket is being created for an upload or data integration process.
     * @return a new PersonalFilestoreTicket used to keep track of files generated by the given Person (either uploaded or via data integration)
     */
    @Transactional
    public PersonalFilestoreTicket createPersonalFilestoreTicket(TdarUser person, PersonalFileType fileType) {
        PersonalFilestoreTicket tfg = new PersonalFilestoreTicket();
        tfg.setSubmitter(person);
        tfg.setPersonalFileType(fileType);
        genericDao.save(tfg);

        // FIXME: it uses the ID as the ticket, but needs to check whether the ticket actually exists
        return tfg;
    }

    /**
     * Returns a personal filestore for the given user.
     * FIXME: should this be based on the PersonalFilestoreTicket instead?
     * 
     * @param submitter
     * @return a properly synchronized filestore for the given user.
     */
    public synchronized PersonalFilestore getPersonalFilestore(TdarUser submitter) {
        PersonalFilestore personalFilestore = personalFilestoreCache.get(submitter);
        if (personalFilestore == null) {
            personalFilestore = new BagitPersonalFilestore();
            personalFilestoreCache.put(submitter, personalFilestore);
        }
        return personalFilestore;
    }

    /**
     * Find a @link PersonalFilestoreTicket based on the ID
     * 
     * @param ticketId
     * @return
     */
    @Transactional(readOnly = true)
    public PersonalFilestoreTicket findPersonalFilestoreTicket(Long ticketId) {
        return genericDao.find(PersonalFilestoreTicket.class, ticketId);
    }

    /**
     * Return all files in the @link PersonalFilestore based on the ticketId
     * 
     * @param ticketId
     * @return
     */
    @Transactional(readOnly = true)
    public List<PersonalFilestoreFile> retrieveAllPersonalFilestoreFiles(Long ticketId) {
        PersonalFilestoreTicket ticket = findPersonalFilestoreTicket(ticketId);
        if (ticket == null) {
            return Collections.emptyList();
        }
        return getPersonalFilestore(ticket.getSubmitter()).retrieveAll(ticket);
    }

    /**
     * Get the @link PersonalFilestore
     * 
     * @param ticket
     * @return
     */
    public synchronized PersonalFilestore getPersonalFilestore(PersonalFilestoreTicket ticket) {
        return getPersonalFilestore(ticket.getSubmitter());
    }

    /**
     * Get a filestore given a ticket
     * 
     * @param ticketId
     * @return
     */
    @Transactional(readOnly = true)
    public synchronized PersonalFilestore getPersonalFilestore(Long ticketId) {
        PersonalFilestoreTicket ticket = findPersonalFilestoreTicket(ticketId);
        return getPersonalFilestore(ticket);
    }

    /**
     * Store a file in the Personal Filestore
     * 
     * @param ticket
     * @param file
     * @param filename
     * @return
     * @throws IOException
     */
    public synchronized PersonalFilestoreFile store(PersonalFilestoreTicket ticket, File file, String filename) throws IOException {
        return getPersonalFilestore(ticket.getSubmitter()).store(ticket, file, filename);
    }

}
