//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.11 at 04:55:08 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = org.tdar.URLConstants.TDAR_NAMESPACE_URL,
        xmlns = {
                @javax.xml.bind.annotation.XmlNs(prefix = "tdar-oai",
                        namespaceURI = org.tdar.URLConstants.TDAR_NAMESPACE_URL)
        },location="http://www.tdar.org/schema",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.tdar.oai.bean;