//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.11 at 04:55:08 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.tdar.org/oai", 
                xmlns = {
                @javax.xml.bind.annotation.XmlNs(prefix = "tdar-oai",
                        namespaceURI = "http://www.tdar.org/oai")
        },elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.tdar.oai.bean;