package org.tdar.search.query;

public interface QueryFieldNames {

    final String PROJECT_ID = "projectId";
    final String RESOURCE_TYPE = "resourceType";
    final String STATUS = "status";
    final String ACTIVE_START_DATE = "activeCoverageDates.startDate";
    final String ACTIVE_END_DATE = "activeCoverageDates.endDate";
    final String DATE = "date";
    final String DATE_UPDATED = "dateUpdated";
    final String DATE_CREATED = "dateCreated";
    final String LABEL = "label";
    final String DOT = ".";
    final String DOT_LABEL = DOT + LABEL;
    final String IR = "informationResources.";
    final String TITLE = "title";
    final String TITLE_AUTO = "title_auto";
    final String PROJECT_TITLE = "project.title";
    final String PROJECT_TITLE_AUTO = "project.title_auto";
    final String TITLE_SORT = "title_sort";
    final String DOCUMENT_TYPE = "documentType";
    final String INTEGRATABLE = "integratable";
    final String SUBMITTER_ID = "submitter.id";
    final String RESOURCE_CREATORS_CREATOR_ID = "resourceCreators.creator.id";
    final String RESOURCE_CREATORS_CREATOR_NAME_KEYWORD = "resourceCreators.creator.name_kwd";
    final String ACTIVE_SITE_TYPE_KEYWORDS = "activeSiteTypeKeywords";
    final String ACTIVE_MATERIAL_KEYWORDS = "activeMaterialKeywords";
    final String ACTIVE_CULTURE_KEYWORDS = "activeCultureKeywords";
    final String ACTIVE_SITE_NAME_KEYWORDS = "activeSiteNameKeywords";
    final String ACTIVE_INVESTIGATION_TYPES = "activeInvestigationTypes";
    final String ACTIVE_GEOGRAPHIC_KEYWORDS = "activeGeographicKeywords";
    final String ACTIVE_OTHER_KEYWORDS = "activeOtherKeywords";
    final String ACTIVE_LATITUDE_LONGITUDE_BOXES = "activeLatitudeLongitudeBoxes";

    final String MAXX = ACTIVE_LATITUDE_LONGITUDE_BOXES + DOT + "maxx";
    final String MAXY = ACTIVE_LATITUDE_LONGITUDE_BOXES + DOT + "maxy";
    final String MINY = ACTIVE_LATITUDE_LONGITUDE_BOXES + DOT + "miny";
    final String MINX = ACTIVE_LATITUDE_LONGITUDE_BOXES + DOT + "minx";
    final String SCALE = ACTIVE_LATITUDE_LONGITUDE_BOXES + DOT + "scale";
    final String MINXPRIME = ACTIVE_LATITUDE_LONGITUDE_BOXES + DOT + "minxPrime";
    final String MAXXPRIME = ACTIVE_LATITUDE_LONGITUDE_BOXES + DOT + "maxxPrime";

    final String ACTIVE_TEMPORAL_KEYWORDS = "activeTemporalKeywords";
    final String ACTIVE_SITE_TYPE_KEYWORDS_LABEL = ACTIVE_SITE_TYPE_KEYWORDS + DOT_LABEL;
    final String ACTIVE_CULTURE_KEYWORDS_LABEL = ACTIVE_CULTURE_KEYWORDS + DOT_LABEL;
    final String ACTIVE_GEOGRAPHIC_KEYWORDS_LABEL = ACTIVE_GEOGRAPHIC_KEYWORDS + DOT_LABEL;
    final String IR_ACTIVE_CULTURE_KEYWORDS_LABEL = IR + ACTIVE_CULTURE_KEYWORDS + DOT_LABEL;
    final String IR_ACTIVE_SITE_TYPE_KEYWORDS_LABEL = IR + ACTIVE_SITE_TYPE_KEYWORDS + DOT_LABEL;
    final String ACTIVE_COVERAGE_TYPE = "activeCoverageDates.dateType";
    final String NAME = "name";
    final String FIRST_NAME = "firstName";
    final String LAST_NAME = "lastName";
    final String EMAIL = "email";
    final String ID = "id";
    final String ALL = "all";
    final String ALL_PHRASE = "allPhrase";
    final String CONTENT = "content";
    final String DESCRIPTION = "description";
    final String PROJECT_TITLE_SORT = "project_title_sort";
    final String LABEL_SORT = "label_sort";
    final String FIRST_NAME_SORT = "firstName_sort";
    final String LAST_NAME_SORT = "lastName_sort";
    final String CREATOR_NAME_SORT = "creator_name_sort";

    final String COLLECTION_NAME = TITLE;
    final String COLLECTION_NAME_AUTO = TITLE_AUTO;
    final String COLLECTION_TYPE = "type";
    final String RESOURCE_USERS_WHO_CAN_VIEW = "usersWhoCanView";
    final String RESOURCE_USERS_WHO_CAN_MODIFY = "usersWhoCanModify";
    final String COLLECTION_USERS_WHO_CAN_ADMINISTER = "usersWhoCanAdminister";
    final String COLLECTION_USERS_WHO_CAN_VIEW = RESOURCE_USERS_WHO_CAN_VIEW;
    final String COLLECTION_USERS_WHO_CAN_MODIFY = RESOURCE_USERS_WHO_CAN_MODIFY;
    // final String RESOURCE_COLLECTION_PUBLIC_IDS = "publicCollectionIds";
    final String RESOURCE_COLLECTION_SHARED_IDS = "sharedCollectionIds";
    final String RESOURCE_ACCESS_TYPE = "resourceAccessType";
    final String PROPER_NAME = "properName";
    final String RESOURCE_CREATORS_PROPER_NAME = "resourceCreators.creator." + PROPER_NAME;
    final String INFORMATION_RESOURCE_FILES_FILENAME = "informationResourceFiles.filename";
    final String RESOURCE_PROVIDER_ID = "resourceProviderInstitution.id";
    final String CATEGORY_ID = "categoryVariable.id";
    final String CATEGORY_LABEL = "categoryVariable.label";
    final String COLLECTION_VISIBLE = "visible";
    final String TOP_LEVEL = "topLevel";
    final String RESOURCE_TYPE_SORT = "resourceTypeSort";
    final String RESOURCE_OWNER = "resourceOwner";
    final String DATE_CREATED_DECADE = "decadeCreated";
    final String CREATOR_ROLE_IDENTIFIER = "crid";
    final String FILENAME = "filename";
    final String DATA_VALUE_PAIR = "dataValuePair";
    final String COLLECTION_TREE = "collection.parentTree";
    final String SITE_CODE = "siteCode";

}
