insert into culture_keyword (label, index, approved, selectable) values ('Pre-Clovis', '1', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('PaleoIndian', '2', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Clovis', '2.1', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Folsom', '2.2', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Dalton', '2.3', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Archaic', '3', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Early Archaic', '3.1', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Middle Archaic', '3.2', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Late Archaic', '3.3', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Hopewell', '4', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Woodland', '5', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Early Woodland', '5.1', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Middle Woodland', '5.2', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Late Woodland', '5.3', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Plains Village', '6', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Mississippian', '7', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Ancestral Puebloan', '8', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Anasazi', '9', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Hohokam', '10', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Mogollon', '11', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Patayan', '12', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Fremont', '13', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Historic', '14', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('African American', '14.1', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Chinese American', '14.2', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Euroamerican', '14.3', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Japanese American', '14.4', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Native American', '14.5', true, true);
insert into culture_keyword (label, index, approved, selectable) values ('Spanish', '14.6', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Domestic Structure or Architectural Complex', '1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('General', '1.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Encampment', '1.1.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Settlement', '1.1.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Hamlet / Village', '1.1.2.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Town / City', '1.1.2.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Specific', '1.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Apartment', '1.2.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Brush structure', '1.2.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Compound', '1.2.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Earth lodge', '1.2.4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('House', '1.2.5', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('House Mound', '1.2.6', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Wattle and daub(jacal) structure', '1.2.7', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Long house', '1.2.8', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Pit house / pit structure', '1.2.9', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Room block / pueblo', '1.2.10', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Rock shelter / cave', '1.2.11', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Shade structure / ramada', '1.2.12', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Tent / Tipi Ring', '1.2.13', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Resource Extraction / Production / Transportation', '2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Agricultural', '2.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Agricultural Field or Field Feature (e.g. boundary marker)', '2.1.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Canal or Canal Feature( e.g. headgate)', '2.1.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Reservoir', '2.1.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Terrace', '2.1.4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Water Control Feature (e.g. check dam)', '2.1.5', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Commercial / Industrial Structures', '2.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Factory/Workshop', '2.2.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Mill', '2.2.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Grist mill', '2.2.2.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Saw mill', '2.2.2.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Shop', '2.2.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Fishing', '2.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Fish trap', '2.3.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Ladder', '2.3.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Wier', '2.3.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Herding', '2.4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Brush corral', '2.4.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Fence', '2.4.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Hunting / Trapping', '2.5', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Butchering / kill site', '2.5.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Hunting blind', '2.5.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Large game jump', '2.5.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Mine (Tunnels)', '2.6', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Mine tunnels', '2.6.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Mine-related structures', '2.6.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Quarry (Surface)', '2.7', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Road / Trail', '2.8', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Bridge', '2.8.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Causeway', '2.8.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Linear feature', '2.8.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Railroad', '2.8.4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Road', '2.8.5', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Trail (including Chacoan Road)', '2.8.6', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Funerary / Burial', '3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Cemetary', '3.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Burial mound', '3.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Charnal house', '3.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Isolated burial', '3.4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Ossuary', '3.5', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Other Structures', '4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Ball Court', '4.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Church / Religious Structure', '4.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Ancient Church / Religious Structure', '4.2.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Prehistoric Church / Religious Structure', '4.2.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Communal/Public Structure (interpretive)', '4.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Ancient Communal / Public Structure (interpretive)', '4.3.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Historic Communal / Public Structure (interpretive)', '4.3.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Great/Big House (Chaco and Hohokam)', '4.4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Governmental Structure', '4.5', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Ancient Governmental Structure', '4.5.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Historic Governmental Structure', '4.5.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Kiva / Great Kiva', '4.6', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Military Structure', '4.7', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Mound / Earthwork', '4.8', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Building substructure', '4.8.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('House mound', '4.8.1.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Building substructure other than a house mound', '4.8.1.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Burial Mound', '4.8.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Earthwork', '4.8.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Ancient earthwork', '4.8.3.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Historic earthwork', '4.8.3.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Geometric / Effigy / Zoomorphic Mound', '4.8.4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('House Mound', '4.8.5', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Mound (undifferentiated)', '4.8.6', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Platform Mound', '4.8.7', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Shell Mound (lived in or on)', '4.8.8', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Tel (recognizable height based on successive occupations)', '4.8.9', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Palace', '4.9', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Palisade', '4.10', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Plaza', '4.11', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Pyramid', '4.12', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Stairway (MesoAmerican)', '4.13', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Structure (architectural remnant of building of unknown form or function)', '4.14', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Ancient Structure', '4.14.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Historic Structure', '4.14.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Sweat House / Sweat Lodge', '4.15', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Temple (MesoAmerican)', '4.16', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Other Archaeological Features', '5', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Artifact Scatter', '5.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Cairn', '5.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Fence', '5.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Hearth', '5.4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Isolated Artifact', '5.5', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Isolated Feature', '5.6', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Kiln', '5.7', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Midden', '5.8', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Burned rock midden', '5.8.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Sheet midden', '5.8.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Shell midden', '5.8.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Trash midden', '5.8.4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Milling Feature', '5.9', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Bedrock grinding', '5.9.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Bedrock mortar', '5.9.1.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Bedrock metate', '5.9.1.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Milling bin', '5.9.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Oven', '5.10', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Pit', '5.11', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Burial pit', '5.11.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Refuse pit', '5.11.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Roasting pit / horno', '5.11.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Storage pit', '5.11.4', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Post hole / Post mold', '5.12', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Rock Alignment', '5.13', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Rock Art', '6', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Intaglio / Geoglyph', '6.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Petroglyph', '6.2', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Pictograph', '6.3', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Water Related', '7', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Shipping-related structure (e.g. dock or wharf)', '7.1', true, true);
insert into site_type_keyword (label, index, approved, selectable) values ('Shipwreck', '7.2', true, true);

alter table culture_keyword drop column interval_start;
alter table culture_keyword drop column interval_end;
alter table site_type_keyword drop column interval_start;
alter table site_type_keyword drop column interval_end;

create table material_keyword (id  bigserial not null, definition text, label varchar(255) not null, primary key (id));
alter table resource_material_keyword rename to resource_material_keyword_old;
create table resource_material_keyword (resource_id int8 not null references resource(id), material_keyword_id int8 not null references material_keyword(id), primary key (resource_id, material_keyword_id));

insert into material_keyword (label, definition) values ('Ceramic', 'Historic or prehistoric artifacts made from pottery or fired clay');
insert into material_keyword (label, definition) values ('Chipped Stone', 'Lithic artifacts such as tools, flakes, shatter, or debitage');
insert into material_keyword (label, definition) values ('Dating Sample', 'Material collected for use with dating techniques such as radiocarbon, dendrochronology or archaeomagnetism');
insert into material_keyword (label, definition) values ('Fauna', 'Animal bone remains');
insert into material_keyword (label, definition) values ('Fire Cracked Rock', 'Rocks showing evidence of intense heating or burning, carbon staining, or other indications of changes due to heat.');
insert into material_keyword (label, definition) values ('Glass', 'Historic or prehistoric artifacts made from glass');
insert into material_keyword (label, definition) values ('Ground Stone', 'Lithic artifact formed or finished by polishing the body or edges with an abrasive');
insert into material_keyword (label, definition) values ('Building Materials', 'Materials used for construction (e.g., brick, wood, adobe)');
insert into material_keyword (label, definition) values ('Human Remains', 'The remains of any part of a human');
insert into material_keyword (label, definition) values ('Macrobotanical', 'Plant remains such as fruit, seeds, buds, or other plant parts.');
insert into material_keyword (label, definition) values ('Metal', 'Any prehistoric or historic artifact made of metal (e.g., iron, copper, gold, silver, etc.)');
insert into material_keyword (label, definition) values ('Mineral', 'Natural inorganic substance possessing a definite chemical composition in a crystalline form.');
insert into material_keyword (label, definition) values ('Pollen', 'Use for any microscopic plant remains');
insert into material_keyword (label, definition) values ('Shell', 'Modified or unmodified objects made from mollusc shell.');
insert into material_keyword (label, definition) values ('Wood', 'Modified or unmodified objects made from the roots, trunk, or branches of trees or shrubs.');

insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Ceramic' and r.material_keyword = 'CERAMIC';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Chipped Stone' and r.material_keyword = 'CHIPPED_STONE';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Dating Sample' and r.material_keyword = 'DATING_SAMPLE';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Fauna' and r.material_keyword = 'FAUNA';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Fire Cracked Rock' and r.material_keyword = 'FIRE_CRACKED_ROCK';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Glass' and r.material_keyword = 'GLASS';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Ground Stone' and r.material_keyword = 'GROUND_STONE';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Building Materials' and r.material_keyword = 'BUILDING_MATERIALS';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Human Remains' and r.material_keyword = 'HUMAN_REMAINS';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Macrobotanical' and r.material_keyword = 'MACROBOTANICAL';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Metal' and r.material_keyword = 'METAL';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Mineral' and r.material_keyword = 'MINERAL';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Pollen' and r.material_keyword = 'POLLEN';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Shell' and r.material_keyword = 'SHELL';
insert into resource_material_keyword (resource_id, material_keyword_id) select r.resource_id, k.id from resource_material_keyword_old r, material_keyword k where k.label = 'Wood' and r.material_keyword = 'WOOD';

create table investigation_type (id  bigserial not null, definition text, label varchar(255) not null, primary key (id));
alter table resource_investigation_type rename to resource_investigation_type_old;
create table resource_investigation_type (resource_id int8 not null references resource(id), investigation_type_id int8 not null references investigation_type(id), primary key (resource_id, investigation_type_id));

insert into investigation_type (label, definition) values ('Archaeological Overview', 'A study that involves the synthesis of the archaeological history of investigation and culture history of a location or area.');
insert into investigation_type (label, definition) values ('Architectural Survey', 'An activity employed to gather data on the presence of historic structures in an area. These studies may provide a general understanding of the resources in an area.');
insert into investigation_type (label, definition) values ('Collections Research', 'A study that involves research and analysis of archaeological resources held in a museum, historical society or other repository.');
insert into investigation_type (label, definition) values ('Consultation', 'An activity that involves discussions and meetings with communities, stakeholders, and other interested parties for the purpose of describing proposed archaeological activities and eliciting their comments, perspectives and feedback.');
insert into investigation_type (label, definition) values ('Data Recovery / Excavation', 'Substantial field investigation of an archaeological site (or sites) involving the removal, and systematic recording of, archaeological matrix. These activities often mitigate the adverse effects of a public undertaking.');
insert into investigation_type (label, definition) values ('Methological, Synthetic or Theoretical Research', 'A non-field study of archaeological theory, method or technique. These investigations may also include broadly synthetic regional studies.');
insert into investigation_type (label, definition) values ('Reconnaissance / Survey', 'An activity employed to gather a general impression of the nature and distribution of archaeological or cultural resources in an area. Relatively little field work is conducted in relation to the size of the research area.');
insert into investigation_type (label, definition) values ('Records Search / Inventory Checking', 'An activity involving the discovery and review of information about the sites recorded in a particular area, e.g., checking the site files in an agency''s database, or SHPO office or State Archaeologist office.');
insert into investigation_type (label, definition) values ('Research Design / Data Recovery Plan', 'Activities undertaken to plan and schedule future archaeological research.');
insert into investigation_type (label, definition) values ('Site Evaluation / Testing', 'Fieldwork undertaken to identify the archaeological resources in a given area and to collect information sufficient to evaluate and develop treatment recommendations. Investigations are used to determine the number, location, distribution and condition of archaeological resources.');
insert into investigation_type (label, definition) values ('Site Stabilization', 'An activity that involves the rehabilitation of eroding, slumping, subsiding or otherwise deteriorating archaeological resources, including structures and building materials.');
insert into investigation_type (label, definition) values ('Systematic Survey', 'An activity employed to systematically gather data on the general presence or absence of archaeological resource, to define resource types, or to estimate the distribution of resources in an area. These studies may provide a general understanding of the resources in an area.');

insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Archaeological Overview' and r.investigation_type = 'ARCHAEOLOGICAL_OVERVIEW';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Architectural Survey' and r.investigation_type = 'ARCHITECTURAL_SURVEY';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Collections Research' and r.investigation_type = 'COLLECTIONS_RESEARCH';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Consultation' and r.investigation_type = 'CONSULTATION';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Data Recovery / Excavation' and r.investigation_type = 'DATA_RECOVERY';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Methological, Synthetic or Theoretical Research' and r.investigation_type = 'METHODOLOGICAL';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Reconnaissance / Survey' and r.investigation_type = 'RECONNAISSANCE';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Records Search / Inventory Checking' and r.investigation_type = 'RECORDS_SEARCH';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Research Design / Data Recovery Plan' and r.investigation_type = 'RESEARCH_DESIGN';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Site Evaluation / Testing' and r.investigation_type = 'SITE_EVALUATION';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Site Stabilization' and r.investigation_type = 'SITE_STABILIZATION';
insert into resource_investigation_type (resource_id, investigation_type_id) select r.resource_id, k.id from resource_investigation_type_old r, investigation_type k where k.label = 'Systematic Survey' and r.investigation_type = 'SYSTEMATIC_SURVEY';

drop table resource_investigation_type_old;
drop table resource_material_keyword_old;

