//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 02:23:18 PM MST 
//


package org.tdar.dataone.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.tdar.dataone.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReplicationPolicy_QNAME = new QName("http://ns.dataone.org/service/types/v1", "replicationPolicy");
    private final static QName _Session_QNAME = new QName("http://ns.dataone.org/service/types/v1", "session");
    private final static QName _Subject_QNAME = new QName("http://ns.dataone.org/service/types/v1", "subject");
    private final static QName _Log_QNAME = new QName("http://ns.dataone.org/service/types/v1", "log");
    private final static QName _Replica_QNAME = new QName("http://ns.dataone.org/service/types/v1", "replica");
    private final static QName _LogEntry_QNAME = new QName("http://ns.dataone.org/service/types/v1", "logEntry");
    private final static QName _NodeReference_QNAME = new QName("http://ns.dataone.org/service/types/v1", "nodeReference");
    private final static QName _Checksum_QNAME = new QName("http://ns.dataone.org/service/types/v1", "checksum");
    private final static QName _Group_QNAME = new QName("http://ns.dataone.org/service/types/v1", "group");
    private final static QName _ObjectInfo_QNAME = new QName("http://ns.dataone.org/service/types/v1", "objectInfo");
    private final static QName _SystemMetadata_QNAME = new QName("http://ns.dataone.org/service/types/v1", "systemMetadata");
    private final static QName _ServiceMethodRestriction_QNAME = new QName("http://ns.dataone.org/service/types/v1", "serviceMethodRestriction");
    private final static QName _Services_QNAME = new QName("http://ns.dataone.org/service/types/v1", "services");
    private final static QName _ObjectList_QNAME = new QName("http://ns.dataone.org/service/types/v1", "objectList");
    private final static QName _AccessRule_QNAME = new QName("http://ns.dataone.org/service/types/v1", "accessRule");
    private final static QName _NodeList_QNAME = new QName("http://ns.dataone.org/service/types/v1", "nodeList");
    private final static QName _ObjectLocationList_QNAME = new QName("http://ns.dataone.org/service/types/v1", "objectLocationList");
    private final static QName _SubjectList_QNAME = new QName("http://ns.dataone.org/service/types/v1", "subjectList");
    private final static QName _Identifier_QNAME = new QName("http://ns.dataone.org/service/types/v1", "identifier");
    private final static QName _ObjectFormatList_QNAME = new QName("http://ns.dataone.org/service/types/v1", "objectFormatList");
    private final static QName _NodeReplicationPolicy_QNAME = new QName("http://ns.dataone.org/service/types/v1", "nodeReplicationPolicy");
    private final static QName _AccessPolicy_QNAME = new QName("http://ns.dataone.org/service/types/v1", "accessPolicy");
    private final static QName _Synchronization_QNAME = new QName("http://ns.dataone.org/service/types/v1", "synchronization");
    private final static QName _SubjectInfo_QNAME = new QName("http://ns.dataone.org/service/types/v1", "subjectInfo");
    private final static QName _Node_QNAME = new QName("http://ns.dataone.org/service/types/v1", "node");
    private final static QName _ObjectFormat_QNAME = new QName("http://ns.dataone.org/service/types/v1", "objectFormat");
    private final static QName _Schedule_QNAME = new QName("http://ns.dataone.org/service/types/v1", "schedule");
    private final static QName _ChecksumAlgorithmList_QNAME = new QName("http://ns.dataone.org/service/types/v1", "checksumAlgorithmList");
    private final static QName _Person_QNAME = new QName("http://ns.dataone.org/service/types/v1", "person");
    private final static QName _Service_QNAME = new QName("http://ns.dataone.org/service/types/v1", "service");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tdar.dataone.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Replica }
     * 
     */
    public Replica createReplica() {
        return new Replica();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link Session }
     * 
     */
    public Session createSession() {
        return new Session();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link ReplicationPolicy }
     * 
     */
    public ReplicationPolicy createReplicationPolicy() {
        return new ReplicationPolicy();
    }

    /**
     * Create an instance of {@link ServiceMethodRestriction }
     * 
     */
    public ServiceMethodRestriction createServiceMethodRestriction() {
        return new ServiceMethodRestriction();
    }

    /**
     * Create an instance of {@link Checksum }
     * 
     */
    public Checksum createChecksum() {
        return new Checksum();
    }

    /**
     * Create an instance of {@link NodeReference }
     * 
     */
    public NodeReference createNodeReference() {
        return new NodeReference();
    }

    /**
     * Create an instance of {@link LogEntry }
     * 
     */
    public LogEntry createLogEntry() {
        return new LogEntry();
    }

    /**
     * Create an instance of {@link ObjectInfo }
     * 
     */
    public ObjectInfo createObjectInfo() {
        return new ObjectInfo();
    }

    /**
     * Create an instance of {@link SystemMetadata }
     * 
     */
    public SystemMetadata createSystemMetadata() {
        return new SystemMetadata();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link ObjectFormatList }
     * 
     */
    public ObjectFormatList createObjectFormatList() {
        return new ObjectFormatList();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link ObjectLocationList }
     * 
     */
    public ObjectLocationList createObjectLocationList() {
        return new ObjectLocationList();
    }

    /**
     * Create an instance of {@link SubjectList }
     * 
     */
    public SubjectList createSubjectList() {
        return new SubjectList();
    }

    /**
     * Create an instance of {@link NodeReplicationPolicy }
     * 
     */
    public NodeReplicationPolicy createNodeReplicationPolicy() {
        return new NodeReplicationPolicy();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link AccessRule }
     * 
     */
    public AccessRule createAccessRule() {
        return new AccessRule();
    }

    /**
     * Create an instance of {@link NodeList }
     * 
     */
    public NodeList createNodeList() {
        return new NodeList();
    }

    /**
     * Create an instance of {@link ObjectList }
     * 
     */
    public ObjectList createObjectList() {
        return new ObjectList();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link ObjectFormat }
     * 
     */
    public ObjectFormat createObjectFormat() {
        return new ObjectFormat();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link ChecksumAlgorithmList }
     * 
     */
    public ChecksumAlgorithmList createChecksumAlgorithmList() {
        return new ChecksumAlgorithmList();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Synchronization }
     * 
     */
    public Synchronization createSynchronization() {
        return new Synchronization();
    }

    /**
     * Create an instance of {@link AccessPolicy }
     * 
     */
    public AccessPolicy createAccessPolicy() {
        return new AccessPolicy();
    }

    /**
     * Create an instance of {@link SubjectInfo }
     * 
     */
    public SubjectInfo createSubjectInfo() {
        return new SubjectInfo();
    }

    /**
     * Create an instance of {@link ObjectLocation }
     * 
     */
    public ObjectLocation createObjectLocation() {
        return new ObjectLocation();
    }

    /**
     * Create an instance of {@link Slice }
     * 
     */
    public Slice createSlice() {
        return new Slice();
    }

    /**
     * Create an instance of {@link Ping }
     * 
     */
    public Ping createPing() {
        return new Ping();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReplicationPolicy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "replicationPolicy")
    public JAXBElement<ReplicationPolicy> createReplicationPolicy(ReplicationPolicy value) {
        return new JAXBElement<ReplicationPolicy>(_ReplicationPolicy_QNAME, ReplicationPolicy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Session }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "session")
    public JAXBElement<Session> createSession(Session value) {
        return new JAXBElement<Session>(_Session_QNAME, Session.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Subject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "subject")
    public JAXBElement<Subject> createSubject(Subject value) {
        return new JAXBElement<Subject>(_Subject_QNAME, Subject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Log }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "log")
    public JAXBElement<Log> createLog(Log value) {
        return new JAXBElement<Log>(_Log_QNAME, Log.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Replica }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "replica")
    public JAXBElement<Replica> createReplica(Replica value) {
        return new JAXBElement<Replica>(_Replica_QNAME, Replica.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogEntry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "logEntry")
    public JAXBElement<LogEntry> createLogEntry(LogEntry value) {
        return new JAXBElement<LogEntry>(_LogEntry_QNAME, LogEntry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "nodeReference")
    public JAXBElement<NodeReference> createNodeReference(NodeReference value) {
        return new JAXBElement<NodeReference>(_NodeReference_QNAME, NodeReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Checksum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "checksum")
    public JAXBElement<Checksum> createChecksum(Checksum value) {
        return new JAXBElement<Checksum>(_Checksum_QNAME, Checksum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "group")
    public JAXBElement<Group> createGroup(Group value) {
        return new JAXBElement<Group>(_Group_QNAME, Group.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "objectInfo")
    public JAXBElement<ObjectInfo> createObjectInfo(ObjectInfo value) {
        return new JAXBElement<ObjectInfo>(_ObjectInfo_QNAME, ObjectInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemMetadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "systemMetadata")
    public JAXBElement<SystemMetadata> createSystemMetadata(SystemMetadata value) {
        return new JAXBElement<SystemMetadata>(_SystemMetadata_QNAME, SystemMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceMethodRestriction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "serviceMethodRestriction")
    public JAXBElement<ServiceMethodRestriction> createServiceMethodRestriction(ServiceMethodRestriction value) {
        return new JAXBElement<ServiceMethodRestriction>(_ServiceMethodRestriction_QNAME, ServiceMethodRestriction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Services }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "services")
    public JAXBElement<Services> createServices(Services value) {
        return new JAXBElement<Services>(_Services_QNAME, Services.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "objectList")
    public JAXBElement<ObjectList> createObjectList(ObjectList value) {
        return new JAXBElement<ObjectList>(_ObjectList_QNAME, ObjectList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessRule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "accessRule")
    public JAXBElement<AccessRule> createAccessRule(AccessRule value) {
        return new JAXBElement<AccessRule>(_AccessRule_QNAME, AccessRule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "nodeList")
    public JAXBElement<NodeList> createNodeList(NodeList value) {
        return new JAXBElement<NodeList>(_NodeList_QNAME, NodeList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectLocationList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "objectLocationList")
    public JAXBElement<ObjectLocationList> createObjectLocationList(ObjectLocationList value) {
        return new JAXBElement<ObjectLocationList>(_ObjectLocationList_QNAME, ObjectLocationList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "subjectList")
    public JAXBElement<SubjectList> createSubjectList(SubjectList value) {
        return new JAXBElement<SubjectList>(_SubjectList_QNAME, SubjectList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Identifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "identifier")
    public JAXBElement<Identifier> createIdentifier(Identifier value) {
        return new JAXBElement<Identifier>(_Identifier_QNAME, Identifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectFormatList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "objectFormatList")
    public JAXBElement<ObjectFormatList> createObjectFormatList(ObjectFormatList value) {
        return new JAXBElement<ObjectFormatList>(_ObjectFormatList_QNAME, ObjectFormatList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeReplicationPolicy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "nodeReplicationPolicy")
    public JAXBElement<NodeReplicationPolicy> createNodeReplicationPolicy(NodeReplicationPolicy value) {
        return new JAXBElement<NodeReplicationPolicy>(_NodeReplicationPolicy_QNAME, NodeReplicationPolicy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessPolicy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "accessPolicy")
    public JAXBElement<AccessPolicy> createAccessPolicy(AccessPolicy value) {
        return new JAXBElement<AccessPolicy>(_AccessPolicy_QNAME, AccessPolicy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Synchronization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "synchronization")
    public JAXBElement<Synchronization> createSynchronization(Synchronization value) {
        return new JAXBElement<Synchronization>(_Synchronization_QNAME, Synchronization.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "subjectInfo")
    public JAXBElement<SubjectInfo> createSubjectInfo(SubjectInfo value) {
        return new JAXBElement<SubjectInfo>(_SubjectInfo_QNAME, SubjectInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Node }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "node")
    public JAXBElement<Node> createNode(Node value) {
        return new JAXBElement<Node>(_Node_QNAME, Node.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectFormat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "objectFormat")
    public JAXBElement<ObjectFormat> createObjectFormat(ObjectFormat value) {
        return new JAXBElement<ObjectFormat>(_ObjectFormat_QNAME, ObjectFormat.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Schedule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "schedule")
    public JAXBElement<Schedule> createSchedule(Schedule value) {
        return new JAXBElement<Schedule>(_Schedule_QNAME, Schedule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChecksumAlgorithmList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "checksumAlgorithmList")
    public JAXBElement<ChecksumAlgorithmList> createChecksumAlgorithmList(ChecksumAlgorithmList value) {
        return new JAXBElement<ChecksumAlgorithmList>(_ChecksumAlgorithmList_QNAME, ChecksumAlgorithmList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "person")
    public JAXBElement<Person> createPerson(Person value) {
        return new JAXBElement<Person>(_Person_QNAME, Person.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Service }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.dataone.org/service/types/v1", name = "service")
    public JAXBElement<Service> createService(Service value) {
        return new JAXBElement<Service>(_Service_QNAME, Service.class, null, value);
    }

}
