//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 02:23:18 PM MST 
//


package org.tdar.dataone.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An ObjectFormatList is the structure returned from the
 *       :func:`CNCore.listFormats()` method of the CN REST interface. It
 *       provides a list of named object formats defined in the DataONE system.
 *       Each :class:`Types.ObjectFormat` returned in the list describes the
 *       object format via its name, and future versions may contain additional
 *       structured content from common external typing systems.
 *       
 * 
 * <p>Java class for ObjectFormatList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectFormatList">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ns.dataone.org/service/types/v1}Slice">
 *       &lt;sequence>
 *         &lt;element name="objectFormat" type="{http://ns.dataone.org/service/types/v1}ObjectFormat" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectFormatList", propOrder = {
    "objectFormat"
})
public class ObjectFormatList
    extends Slice
{

    @XmlElement(required = true)
    protected List<ObjectFormat> objectFormat;

    /**
     * Gets the value of the objectFormat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectFormat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectFormat }
     * 
     * 
     */
    public List<ObjectFormat> getObjectFormat() {
        if (objectFormat == null) {
            objectFormat = new ArrayList<ObjectFormat>();
        }
        return this.objectFormat;
    }

}
