//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 02:23:18 PM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.dataone.org/service/types/v1")
package org.tdar.dataone.bean;


// generated from: xjc -p org.tdar.dataone.bean "http://ns.dataone.org/service/types/v1"