//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 02:23:18 PM MST 
//


package org.tdar.dataone.bean;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReplicationStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReplicationStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="queued"/>
 *     &lt;enumeration value="requested"/>
 *     &lt;enumeration value="completed"/>
 *     &lt;enumeration value="failed"/>
 *     &lt;enumeration value="invalidated"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReplicationStatus")
@XmlEnum
public enum ReplicationStatus {

    @XmlEnumValue("queued")
    QUEUED("queued"),
    @XmlEnumValue("requested")
    REQUESTED("requested"),
    @XmlEnumValue("completed")
    COMPLETED("completed"),
    @XmlEnumValue("failed")
    FAILED("failed"),
    @XmlEnumValue("invalidated")
    INVALIDATED("invalidated");
    private final String value;

    ReplicationStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReplicationStatus fromValue(String v) {
        for (ReplicationStatus c: ReplicationStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
