//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 02:23:18 PM MST 
//


package org.tdar.dataone.bean;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * The *ReplicationPolicy* for an object defines if
 *       replication should be attempted for this object, and if so, how many
 *       replicas should be maintained. It also permits specification of
 *       preferred and blocked nodes as potential replication targets.
 *       
 * 
 * <p>Java class for ReplicationPolicy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReplicationPolicy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="preferredMemberNode" type="{http://ns.dataone.org/service/types/v1}NodeReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="blockedMemberNode" type="{http://ns.dataone.org/service/types/v1}NodeReference" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="replicationAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="numberReplicas" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReplicationPolicy", propOrder = {
    "preferredMemberNode",
    "blockedMemberNode"
})
public class ReplicationPolicy {

    protected List<NodeReference> preferredMemberNode;
    protected List<NodeReference> blockedMemberNode;
    @XmlAttribute(name = "replicationAllowed")
    protected Boolean replicationAllowed;
    @XmlAttribute(name = "numberReplicas")
    protected Integer numberReplicas;

    /**
     * Gets the value of the preferredMemberNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preferredMemberNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreferredMemberNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NodeReference }
     * 
     * 
     */
    public List<NodeReference> getPreferredMemberNode() {
        if (preferredMemberNode == null) {
            preferredMemberNode = new ArrayList<NodeReference>();
        }
        return this.preferredMemberNode;
    }

    /**
     * Gets the value of the blockedMemberNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blockedMemberNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlockedMemberNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NodeReference }
     * 
     * 
     */
    public List<NodeReference> getBlockedMemberNode() {
        if (blockedMemberNode == null) {
            blockedMemberNode = new ArrayList<NodeReference>();
        }
        return this.blockedMemberNode;
    }

    /**
     * Gets the value of the replicationAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReplicationAllowed() {
        return replicationAllowed;
    }

    /**
     * Sets the value of the replicationAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReplicationAllowed(Boolean value) {
        this.replicationAllowed = value;
    }

    /**
     * Gets the value of the numberReplicas property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberReplicas() {
        return numberReplicas;
    }

    /**
     * Sets the value of the numberReplicas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberReplicas(Integer value) {
        this.numberReplicas = value;
    }

}
