//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 02:23:18 PM MST 
//


package org.tdar.dataone.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Replica information that describes the existence of a
 *       replica of some object managed by the DataONE infrastructure, and its 
 *       status.
 * 
 * <p>Java class for Replica complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Replica">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="replicaMemberNode" type="{http://ns.dataone.org/service/types/v1}NodeReference"/>
 *         &lt;element name="replicationStatus" type="{http://ns.dataone.org/service/types/v1}ReplicationStatus"/>
 *         &lt;element name="replicaVerified" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Replica", propOrder = {
    "replicaMemberNode",
    "replicationStatus",
    "replicaVerified"
})
public class Replica {

    @XmlElement(required = true)
    protected NodeReference replicaMemberNode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ReplicationStatus replicationStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar replicaVerified;

    /**
     * Gets the value of the replicaMemberNode property.
     * 
     * @return
     *     possible object is
     *     {@link NodeReference }
     *     
     */
    public NodeReference getReplicaMemberNode() {
        return replicaMemberNode;
    }

    /**
     * Sets the value of the replicaMemberNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeReference }
     *     
     */
    public void setReplicaMemberNode(NodeReference value) {
        this.replicaMemberNode = value;
    }

    /**
     * Gets the value of the replicationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ReplicationStatus }
     *     
     */
    public ReplicationStatus getReplicationStatus() {
        return replicationStatus;
    }

    /**
     * Sets the value of the replicationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplicationStatus }
     *     
     */
    public void setReplicationStatus(ReplicationStatus value) {
        this.replicationStatus = value;
    }

    /**
     * Gets the value of the replicaVerified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReplicaVerified() {
        return replicaVerified;
    }

    /**
     * Sets the value of the replicaVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReplicaVerified(XMLGregorianCalendar value) {
        this.replicaVerified = value;
    }

}
