//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 02:23:18 PM MST 
//


package org.tdar.dataone.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about the authenticated session for a
 *       service transaction. Session data is retrieved from the SSL client
 *       certificate and populated in the *Session* object. The subject
 *       represents the person or system that authenticated successfully, and the
 *       *subjectInfo* contains a listing of alternate identities (both Persons
 *       and Groups) that are also valid identities for this user. The
 *       *subjectInfo* should include at least one :class:`Types.Person` or
 *       :class:`Types.Group` entry that provides the attributes of the subject
 *       that was authenticated.
 * 
 * <p>Java class for Session complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Session">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subject" type="{http://ns.dataone.org/service/types/v1}Subject"/>
 *         &lt;element name="subjectInfo" type="{http://ns.dataone.org/service/types/v1}SubjectInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Session", propOrder = {
    "subject",
    "subjectInfo"
})
public class Session {

    @XmlElement(required = true)
    protected Subject subject;
    protected SubjectInfo subjectInfo;

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link Subject }
     *     
     */
    public Subject getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subject }
     *     
     */
    public void setSubject(Subject value) {
        this.subject = value;
    }

    /**
     * Gets the value of the subjectInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectInfo }
     *     
     */
    public SubjectInfo getSubjectInfo() {
        return subjectInfo;
    }

    /**
     * Sets the value of the subjectInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectInfo }
     *     
     */
    public void setSubjectInfo(SubjectInfo value) {
        this.subjectInfo = value;
    }

}
