//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 02:23:18 PM MST 
//


package org.tdar.dataone.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Configuration information for the process by which
 *       metadata is harvested from Member Nodes to Coordinating Nodes, including
 *       the schedule on which harvesting should occur, and information about the
 *       last :term:`synchronization` attempts for the node. Member Nodes
 *       providing *Synchronization* information only need to provide the
 *       *schedule*. Coordinating Nodes must set values for the *lastHarvested*
 *       and *lastCompleteHarvest* fields.
 * 
 * <p>Java class for Synchronization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Synchronization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="schedule" type="{http://ns.dataone.org/service/types/v1}Schedule"/>
 *         &lt;element name="lastHarvested" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="lastCompleteHarvest" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Synchronization", propOrder = {
    "schedule",
    "lastHarvested",
    "lastCompleteHarvest"
})
public class Synchronization {

    @XmlElement(required = true)
    protected Schedule schedule;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastHarvested;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastCompleteHarvest;

    /**
     * Gets the value of the schedule property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule }
     *     
     */
    public Schedule getSchedule() {
        return schedule;
    }

    /**
     * Sets the value of the schedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule }
     *     
     */
    public void setSchedule(Schedule value) {
        this.schedule = value;
    }

    /**
     * Gets the value of the lastHarvested property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastHarvested() {
        return lastHarvested;
    }

    /**
     * Sets the value of the lastHarvested property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastHarvested(XMLGregorianCalendar value) {
        this.lastHarvested = value;
    }

    /**
     * Gets the value of the lastCompleteHarvest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastCompleteHarvest() {
        return lastCompleteHarvest;
    }

    /**
     * Sets the value of the lastCompleteHarvest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastCompleteHarvest(XMLGregorianCalendar value) {
        this.lastCompleteHarvest = value;
    }

}
