//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 02:23:18 PM MST 
//


package org.tdar.dataone.bean;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *  System Metadata elements are partitioned into two
 *       classes: metadata elements that must be provided by client software to
 *       the DataONE system, and elements that are generated by DataONE itself in
 *       the course of managing objects. 
 * 
 * <p>Java class for SystemMetadata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SystemMetadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serialVersion" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://ns.dataone.org/service/types/v1}Identifier"/>
 *         &lt;element name="formatId" type="{http://ns.dataone.org/service/types/v1}ObjectFormatIdentifier"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="checksum" type="{http://ns.dataone.org/service/types/v1}Checksum"/>
 *         &lt;element name="submitter" type="{http://ns.dataone.org/service/types/v1}Subject" minOccurs="0"/>
 *         &lt;element name="rightsHolder" type="{http://ns.dataone.org/service/types/v1}Subject"/>
 *         &lt;element name="accessPolicy" type="{http://ns.dataone.org/service/types/v1}AccessPolicy" minOccurs="0"/>
 *         &lt;element name="replicationPolicy" type="{http://ns.dataone.org/service/types/v1}ReplicationPolicy" minOccurs="0"/>
 *         &lt;element name="obsoletes" type="{http://ns.dataone.org/service/types/v1}Identifier" minOccurs="0"/>
 *         &lt;element name="obsoletedBy" type="{http://ns.dataone.org/service/types/v1}Identifier" minOccurs="0"/>
 *         &lt;element name="archived" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="dateUploaded" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dateSysMetadataModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="originMemberNode" type="{http://ns.dataone.org/service/types/v1}NodeReference" minOccurs="0"/>
 *         &lt;element name="authoritativeMemberNode" type="{http://ns.dataone.org/service/types/v1}NodeReference" minOccurs="0"/>
 *         &lt;element name="replica" type="{http://ns.dataone.org/service/types/v1}Replica" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemMetadata", propOrder = {
    "serialVersion",
    "identifier",
    "formatId",
    "size",
    "checksum",
    "submitter",
    "rightsHolder",
    "accessPolicy",
    "replicationPolicy",
    "obsoletes",
    "obsoletedBy",
    "archived",
    "dateUploaded",
    "dateSysMetadataModified",
    "originMemberNode",
    "authoritativeMemberNode",
    "replica"
})
public class SystemMetadata {

    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger serialVersion;
    @XmlElement(required = true)
    protected Identifier identifier;
    @XmlElement(required = true)
    protected String formatId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger size;
    @XmlElement(required = true)
    protected Checksum checksum;
    protected Subject submitter;
    @XmlElement(required = true)
    protected Subject rightsHolder;
    protected AccessPolicy accessPolicy;
    protected ReplicationPolicy replicationPolicy;
    protected Identifier obsoletes;
    protected Identifier obsoletedBy;
    protected Boolean archived;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateUploaded;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateSysMetadataModified;
    protected NodeReference originMemberNode;
    protected NodeReference authoritativeMemberNode;
    protected List<Replica> replica;

    /**
     * Gets the value of the serialVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSerialVersion() {
        return serialVersion;
    }

    /**
     * Sets the value of the serialVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSerialVersion(BigInteger value) {
        this.serialVersion = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setIdentifier(Identifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the formatId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatId() {
        return formatId;
    }

    /**
     * Sets the value of the formatId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatId(String value) {
        this.formatId = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSize(BigInteger value) {
        this.size = value;
    }

    /**
     * Gets the value of the checksum property.
     * 
     * @return
     *     possible object is
     *     {@link Checksum }
     *     
     */
    public Checksum getChecksum() {
        return checksum;
    }

    /**
     * Sets the value of the checksum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Checksum }
     *     
     */
    public void setChecksum(Checksum value) {
        this.checksum = value;
    }

    /**
     * Gets the value of the submitter property.
     * 
     * @return
     *     possible object is
     *     {@link Subject }
     *     
     */
    public Subject getSubmitter() {
        return submitter;
    }

    /**
     * Sets the value of the submitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subject }
     *     
     */
    public void setSubmitter(Subject value) {
        this.submitter = value;
    }

    /**
     * Gets the value of the rightsHolder property.
     * 
     * @return
     *     possible object is
     *     {@link Subject }
     *     
     */
    public Subject getRightsHolder() {
        return rightsHolder;
    }

    /**
     * Sets the value of the rightsHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subject }
     *     
     */
    public void setRightsHolder(Subject value) {
        this.rightsHolder = value;
    }

    /**
     * Gets the value of the accessPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link AccessPolicy }
     *     
     */
    public AccessPolicy getAccessPolicy() {
        return accessPolicy;
    }

    /**
     * Sets the value of the accessPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessPolicy }
     *     
     */
    public void setAccessPolicy(AccessPolicy value) {
        this.accessPolicy = value;
    }

    /**
     * Gets the value of the replicationPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link ReplicationPolicy }
     *     
     */
    public ReplicationPolicy getReplicationPolicy() {
        return replicationPolicy;
    }

    /**
     * Sets the value of the replicationPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplicationPolicy }
     *     
     */
    public void setReplicationPolicy(ReplicationPolicy value) {
        this.replicationPolicy = value;
    }

    /**
     * Gets the value of the obsoletes property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getObsoletes() {
        return obsoletes;
    }

    /**
     * Sets the value of the obsoletes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setObsoletes(Identifier value) {
        this.obsoletes = value;
    }

    /**
     * Gets the value of the obsoletedBy property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getObsoletedBy() {
        return obsoletedBy;
    }

    /**
     * Sets the value of the obsoletedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setObsoletedBy(Identifier value) {
        this.obsoletedBy = value;
    }

    /**
     * Gets the value of the archived property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isArchived() {
        return archived;
    }

    /**
     * Sets the value of the archived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setArchived(Boolean value) {
        this.archived = value;
    }

    /**
     * Gets the value of the dateUploaded property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateUploaded() {
        return dateUploaded;
    }

    /**
     * Sets the value of the dateUploaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateUploaded(XMLGregorianCalendar value) {
        this.dateUploaded = value;
    }

    /**
     * Gets the value of the dateSysMetadataModified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateSysMetadataModified() {
        return dateSysMetadataModified;
    }

    /**
     * Sets the value of the dateSysMetadataModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateSysMetadataModified(XMLGregorianCalendar value) {
        this.dateSysMetadataModified = value;
    }

    /**
     * Gets the value of the originMemberNode property.
     * 
     * @return
     *     possible object is
     *     {@link NodeReference }
     *     
     */
    public NodeReference getOriginMemberNode() {
        return originMemberNode;
    }

    /**
     * Sets the value of the originMemberNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeReference }
     *     
     */
    public void setOriginMemberNode(NodeReference value) {
        this.originMemberNode = value;
    }

    /**
     * Gets the value of the authoritativeMemberNode property.
     * 
     * @return
     *     possible object is
     *     {@link NodeReference }
     *     
     */
    public NodeReference getAuthoritativeMemberNode() {
        return authoritativeMemberNode;
    }

    /**
     * Sets the value of the authoritativeMemberNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeReference }
     *     
     */
    public void setAuthoritativeMemberNode(NodeReference value) {
        this.authoritativeMemberNode = value;
    }

    /**
     * Gets the value of the replica property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the replica property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReplica().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Replica }
     * 
     * 
     */
    public List<Replica> getReplica() {
        if (replica == null) {
            replica = new ArrayList<Replica>();
        }
        return this.replica;
    }

}
