# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile provisions a virtualbox ubuntu 19.04 instance and installs
# Solr v14.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-19.04"
  config.vm.box_version = "201906.18.0"
  config.vm.network "forwarded_port", guest: 8983, host: 8983
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook-vagrant.yml"
  end
end
